import {
  createContext,
  useContext,
  useEffect,
  useState,
  ReactNode,
  useCallback
} from 'react';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';

// ================================================================================================
// TYPE DEFINITIONS
// ================================================================================================

type Language = 'en' | 'el' | 'es' | 'fr' | 'de';

type Translations = Record<string, Record<string, string>>;

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  translations: Translations;
  isLoaded: boolean;
}

// ================================================================================================
// DEFAULT TRANSLATIONS (Complete Object)
// ================================================================================================

const defaultTranslations: Translations = {
  // ================================= English (en) ===================================
  en: {
    // Auth
    email: 'Email',                              password: 'Password',                    forgotPassword: 'Forgot Password?',        register: 'Register',
    signIn: 'Sign In',                           loggingIn: 'Logging in...',              emailPlaceholder: 'email@example.com',     orContinueWith: 'Or continue with',
    google: 'Google',                            facebook: 'Facebook',                    twitter: 'Twitter',                        createAccount: 'Create Account',
    dontHaveAccount: "Don't have an account?",   alreadyHaveAccount: 'Already have an account?', fullName: 'Full Name', confirmPassword: 'Confirm Password',
    agreeToTerms: 'I agree to the Terms of Service and Privacy Policy',
    creatingAccount: 'Creating Account...',      resetYourPassword: 'Reset Your Password',
    enterEmailForReset: 'Enter your email address and we will send you a link to reset your password.',
    sendResetLink: 'Send Reset Link',            sendingResetLink: 'Sending...',
    resetPasswordEmailSent: 'Password reset email sent. Please check your inbox.',
    backToLogin: 'Back to Login',                createNewPassword: 'Create New Password',
    newPassword: 'New Password',                 updatePassword: 'Update Password',
    updating: 'Updating...',                     passwordUpdated: 'Password Updated',
    passwordSuccessfullyChanged: 'Your password has been successfully changed.',
    passwordResetFailed: 'Password Reset Failed',
    errorProcessingRequest: 'There was an error processing your request.',
    passwordTooShort: 'Password Too Short',      passwordMinLength: 'Password must be at least 6 characters.',
    passwordsDontMatch: 'Passwords Don\'t Match', pleaseCheckPasswords: 'Please check that both passwords match.',

    // General UI & Nav
    languageSettings: 'Language Settings',       selectLanguage: 'Select Language',         english: 'English',          greek: 'Greek',
    spanish: 'Spanish',                          french: 'French',                         german: 'German',            systemLanguage: 'System Language (Default)',
    save: 'Save',                                cancel: 'Cancel',                          loading: 'Loading...',       success: 'Success',
    error: 'Error',                              wallet: 'Wallet',                          myWallet: 'My Wallet',       manageWallet: 'Manage your funds, transactions, and ad payments',
    deposit: 'Deposit',                          transactions: 'Transactions',              connectWallet: 'Connect Wallet', addFunds: 'Add Funds',
    amount: 'Amount ($)',                        enterAmount: 'Enter amount',               paymentMethod: 'Payment Method', processing: 'Processing...',
    myAccount: 'My Account',                     profile: 'Profile',                        favorites: 'Favorites',      recentlyViewed: 'Recently Viewed',
    priceAlerts: 'Price Alerts',                 settings: 'Settings',                      logout: 'Logout',            myProfile: 'My Profile',
    managePersonalInfo: 'Manage your personal information',
    name: 'Name',                                memberSince: 'Member since',               role: 'Role',                administrator: 'Administrator',
    regularUser: 'Regular User',                 editProfile: 'Edit Profile',               accountSummary: 'Account Summary', categories: 'Categories',
    gifts: 'Gifts',                              deals: 'Deals',                            clearFilters: 'Clear filters', finalPrice: 'Final price',
    yes: "Yes",                                  no: "No",                                  ok: "OK",                    close: "Close",
    showMore: "Show More",                       showLess: "Show Less",                     all: "All",                  selectOption: "Select an option",
    optional: "Optional",                        required: "Required",                      back: "Back",                next: "Next",
    submit: "Submit",                            search: "Search",                          searchPlaceholder: "Search for products...",
    notFoundPageTitle: "Page Not Found",         notFoundMessage: "Oops! The page you are looking for does not exist.",
    recently_viewed_title: "Recently Viewed",

    // Categories Page & Filters
    "product_singular": "product",               "product_plural": "{{count}} products",
    "rating_label": "Rating",                    "reviews_label_singular": "review",        "reviews_label_plural": "{{count}} reviews",
    "from_vendor": "from",                       "with": "with",
    "no_products_in_category": "There are no products in this category yet.",
    "filters_title": "Filters",                  "remove_all_filters_tooltip": "Remove all filters",
    "show_only_title": "Show only",              "deals_label": "Deals",
    "deals_title": "Products with significant price drop",
    "certified_label": "Certified",              "certified_stores_title": "Certified Stores",
    "instock_label": "In Stock",                 "instock_title": "Only products available in stock",
    "boxnow_delivery_title": "BOX NOW Delivery",
    "boxnow_tooltip": "Pick up your order from a BOX NOW locker 24/7",
    "delivery_label": "BOX NOW",                 "manufacturer_title": "Manufacturer",
    "show_less_manufacturers": "Show less manufacturers", "show_all_manufacturers": "Show all manufacturers",
    "show_all": "Show All",
    "show_less_options": "Show less options for", "show_all_options": "Show all options for",
    "remove_instock_filter": "Remove 'In Stock' filter",    "remove_deals_filter": "Remove 'Deals' filter",
    "remove_certified_filter": "Remove 'Certified' filter", "remove_nearby_filter": "Remove 'Nearby' filter",
    "remove_boxnow_filter": "Remove 'BOX NOW' filter",
    "remove_brand_filter": "Remove brand filter",           "remove_spec_filter": "Remove spec filter",
    "reset_all_filters": "Reset all filters",               "clear_all_filters": "Clear All",
    "selected_deals": "Selected Deals",                     "popular_choices": "Popular Choices",
    "sort_most_popular": "Most Popular",                    "sort_newest": "Newest",
    "sort_cheapest": "Cheapest",                            "sort_most_expensive": "Most Expensive",
    "sort_alphabetical": "Alphabetical (A-Z)",              "sort_most_reviews": "Most Reviews",
    "sort_by_manufacturer": "By Manufacturer",              "sort_num_stores": "Number of Stores",
    "price_alert_for": "Price Alert for",
    "no_products_found_filters": "No products match your current filters.",
    "suggestions_title": "Suggestions",
    "suggestion_see_all_products": "See all products in this category:",
    "all_category_products": "All Category Products",
    "suggestion_try_removing_filters": "Try removing some filters:",
    "remove_a_filter": "Remove a filter",
    "suggestion_return_home": "Return to the homepage:",
    "return_to_homepage": "Return to Homepage",
    "no_subcategories": "No subcategories available.",
    "popular_categories": "Popular Categories",             "top_deals_in": "Top Deals in",
    "products_with_significant_price_drop": "Products with a significant price drop",
    "hottest_in": "Hottest in",                             "product_reviews_title": "Product Reviews",
    "helpful_reviews_subtitle": "Helpful reviews from our users",
    "popular_manufacturers": "Popular Manufacturers",
    "price_alert_button": "Set Price Alert",
    "price_alert_prompt_in": "Never miss a deal for products in",
    "return_to": "Return to",
    "info_for_certified_store": "Information for certified store",
    "showing_products_from_store": "Showing products from store",
    "remove_filter": "Remove this filter",

    // Product Breadcrumb
    "breadcrumbHome": "BestPrice",
    "breadcrumbAllProductsInCategory": "All products in the {{categoryName}} category",
    "breadcrumbAllProductsAndSubcategoriesInCategory": "All products and subcategories in the {{categoryName}} category",

    // Product Detail Page
    "loadingProduct": "Loading Product...",
    "addToShoppingList": "Add to Shopping List", "addToComparison": "Add to Comparison",
    "iWantIt": "I Want It",                      "iHaveIt": "I Have It",
    "notifyPriceDrop": "Notify for Price Drop",  "addToCollection": "Add to Collection",
    "priceFrom": "From",                         "inStores": "in {{count}} stores",
    "storesCount": "Stores ({{count}})",
    "available": "Available",                    "nearMe": "Near Me",
    "deliveryWithService": "Delivery with {{serviceName}}",
    "coupons": "Coupons",                        "color": "Color",
    "officialResellers": "Official Resellers",   "priceHistoryTitle": "Price History",
    "productDetails": "Product Details",         "userReviews": "User Reviews ({{count}})",
    "questionsAndAnswers": "Questions & Answers ({{count}})",
    "similarProducts": "Similar Products",       "dealsInCategory": "Deals in {{categoryName}}",
    "addToCart": "Add to Cart",                  "buyNow": "Buy Now",
    "specifications": "Specifications",          "reviews": "Reviews",
    "relatedProducts": "Related Products",       "writeReview": "Write a Review",
    "outOfStock": "Out of Stock",
    "availableAt": "Available at {{count}} stores", "noStoresAvailable": "Currently unavailable",
    "priceRange": "Price Range",                 "comparePrices": "Compare {{count}} Prices",
    "viewAllStores": "View all stores",          "productDescription": "Description",
    "share": "Share",
    "removeFromFavorites": "Remove from Favorites",
    "priceHistory": "Price History",
    "certifiedStoresTooltip": "Show only products from certified stores",
    "vendorPopupCertification": "Certification: {{certificationType}}",
    "vendorPopupInformation": "Information",
    "vendorPopupAddressNotAvailable": "Online Only Store",
    "vendorPopupPaymentMethods": "PAYMENT METHODS",
    "vendorPopupLearnMore": "Learn More",        "vendorPopupViewInStore": "View in Store",
    "openingHoursNotAvailable": "Opening hours information not available",
    "closedToday": "Closed today",               "openUntil": "Open until {{time}}",
    "closedOpensAt": "Closed - Opens at {{time}}", "closedForToday": "Closed for today",
    "openingHoursError": "Error in opening hours",
    "loginRequired": "Login Required",
    "loginToAddToFavorites": "Please log in to add this product to your favorites",
    "productAddedToFavorites": "{{productName}} has been added to your favorites",
    "linkCopied": "Link Copied",                 "productLinkCopied": "Product link copied to clipboard",
    "copyFailed": "Copy Failed",                 "couldNotCopyLink": "Could not copy link",
    "loginToSetPriceAlert": "Please log in to set a price alert",

    // Vendor Page
    "loadingVendor": "Loading store...", "allStores": "Stores",
    "certifiedStoreLinkText": "Certified Store ({{certificationLevel}})",
    "certifiedStoreFullText": "{{vendorName}} is a certified store ({{certificationLevel}})",
    "memberSinceDate": "On BestPrice since {{date}}",
    "ratingTooltip": "{{rating}} stars from {{count}} ratings",
    "social_facebook": "Facebook", "social_twitter": "Twitter", "social_instagram": "Instagram", "social_youtube": "YouTube", "social_linkedin": "LinkedIn", "social_tiktok": "TikTok",
    "additionalStores": "{{count}} more {{storeLabel}}",
    "storeLabelSingular": "store", "storeLabelPlural": "stores",
    "logoFor": "{{name}} logo", "screenshotFor": "{{name}} Screenshot",
    "authorizedReseller": "Authorized Reseller", "previewWebsite": "Preview Website",
    "dealsFromVendor": "Deals from {{vendorName}}",
    "popularCategoriesInVendor": "Popular Categories in {{vendorName}}",
    "viewAllVendorProducts": "View all products<span class=\"hide-mobile\"> of the store</span>",
    "storeReviewsTitle": "Store Reviews for {{vendorName}}",
    "reviewCount": "{{count}} reviews", "rateIt": "Rate It",
    "reviewsPlaceholder": "(Reviews display - Implementation needed)",
    "servicePointsTitle": "Service Points for {{vendorName}}",
    "servicePointsCount": "{{count}} points",
    "storeAndPickup": "Store / Pickup Point",
    "mapPlaceholderText": "Map Placeholder - Requires Map Library",
    "noLanguagesInRegion": "No languages listed for this region yet.",

    // UserButton & UserDropdownContent
    "toggleTheme": "Toggle theme",
    "productsYouWant": "Products you want",      "productsYouHave": "Products you have",
    "myOffers": "My Offers",                     "priceDrops": "Price Drops",
    "myCollections": "My Collections",           "newCollection": "New Collection...",
    "creditsClub": "Credits Club",               "savedOrders": "Saved Orders",
    "myQuestions": "My Questions",               "myReviews": "My Reviews",
    "myFriends": "My Friends",                   "viewProfileTooltip": "View your profile",
    "userMenuCaretAlt": "Open user menu",

    // Footer
    "backToTop": "Back to Top",
    "bestpriceSloganShort": "The truly best price",
    "bestpriceSloganLong": "BestPrice is the first and largest price comparison service in Greece.",
    "bestpriceSloganFindDeals": "At BestPrice you will quickly and easily find real offers and the best price from the largest stores.",
    "bestpriceGive": "BestPrice Give", "footerBestPriceSectionTitle": "BestPrice",
    "aboutUs": "About Us", "ourBlog": "Our Blog",
    "buyingGuides": "Buying Guides", "purchaseInsurance": "Purchase Insurance",
    "advertising": "Advertising", "bestpriceCertification": "BestPrice Certification",
    "customerReviewAwards": "Customer Review Awards", "ourAwards": "Our Awards",
    "ourTeam": "Our Team", "bestpriceAssistant": "BestPrice Assistant",
    "jobOpenings": "Job Openings ({{count}})", "contactUs": "Contact",
    "inNumbers": "In Numbers",
    "storeCountLink": "{{count}} stores", "productCountLink": "{{count}} products",
    "brandCountLink": "{{count}} manufacturers","dealCountLink": "{{count}} offers",
    "termsAndPrivacy": "Terms & Privacy", "termsOfUse": "Terms of Use",
    "privacyPolicy": "Privacy Policy", "cookiePolicy": "Cookie Policy",
    "gdprLink": "GDPR", "dsaLink": "DSA",
    "bestpriceForMerchants": "BestPrice For Merchants",
    "merchantsSectionSlogan1": "Do you have an online store?",
    "merchantsSectionSlogan2": "See how BestPrice can help you increase your sales!",
    "forMerchantsButton": "For Merchants",
    "bestpriceForBrands": "BestPrice For Brands",
    "brandsSectionSlogan": "BestPrice for Brands will offer useful information & services to manufacturers (Brands).",
    "moreInfoButton": "More Info",
    "bestpriceOnFacebook": "BestPrice on Facebook", "bestpriceOnX": "BestPrice on X",
    "bestpriceOnThreads": "BestPrice on Threads", "bestpriceOnInstagram": "BestPrice on Instagram",
    "bestpriceOnTikTok": "BestPrice on TikTok", "bestpriceOnYouTube": "BestPrice on YouTube",
    "bestpriceOnLinkedIn": "BestPrice on LinkedIn",
    "homepageTitle": "Homepage",
    "changeLanguage": "Change Language", "selectYourLanguageTitle": "Select Your Language",
    "suggestedLanguages": "Suggested Languages", "allLanguages": "All Languages",
    "languageCategoryEurope": "Europe", "languageCategoryAsia": "Asia",
    "languageCategoryAmericas": "Americas", "languageCategoryAfrica": "Africa & Middle East",
    "languageCategoryEasternEurope": "Eastern Europe", "languageCategoryWesternEurope": "Western Europe",

    // Deals, Brands, Search
    "allBrands": "All Brands", "productsFromBrand": "Products from {{brandName}}",
    "searchResultsFor": "Search results for \"{{searchTerm}}\"",
    "noResultsFound": "No results found for \"{{searchTerm}}\"",
    "sortBy": "Sort by", "viewAsGrid": "Grid View",
    "viewAsList": "List View", "itemsPerPage": "Items per page",
    "page": "Page", "of": "of", "nextPage": "Next", "previousPage": "Previous",
    "todaysDeals": "Today's Deals", "filterBy": "Filter by",

    // Cart & Checkout
    "shoppingCart": "Shopping Cart", "proceedToCheckout": "Proceed to Checkout",
    "item": "Item", "quantity": "Quantity", "subtotal": "Subtotal", "total": "Total",
    "emptyCart": "Your cart is empty.", "continueShopping": "Continue Shopping",
    "shippingAddress": "Shipping Address", "billingAddress": "Billing Address",
    "paymentInformation": "Payment Information", "placeOrder": "Place Order",
    "orderSummary": "Order Summary", "discountCode": "Discount Code", "apply": "Apply",

    // Payment Methods (Dynamic Keys)
    "paymentMethod_credit_card": "Credit Card", "paymentMethod_bank_transfer": "Bank Transfer",
    "paymentMethod_paypal": "PayPal", "paymentMethod_cash_on_delivery": "Cash on Delivery",
    "paymentMethod_pickup_from_store": "Pickup from Store", "paymentMethod_klarna": "Klarna",
    "paymentMethod_apple_pay": "Apple Pay", "paymentMethod_google_pay": "Google Pay",
    "paymentMethod_ideal": "iDEAL", "paymentMethod_crypto": "Cryptocurrency",
    "paymentMethod_pay_by_link": "Pay by Link", "paymentMethod_pickup_via": "Pickup via Courier/Service",

    // Category Slugs
    'technology': 'Technology', 'home-garden': 'Home & Garden', 'fashion': 'Fashion',
    'health-beauty': 'Health & Beauty', 'kids-baby': 'Kids & Baby', 'hobby-sports': 'Hobby & Sports',
    'auto-moto': 'Auto & Moto',
    'mobile-telephony': 'Mobile Telephony', 'computers': 'Computers', 'laptops-accessories': 'Laptops & Accessories',
    'visual': 'Visual', 'smartwatches-wearables': 'Smartwatches & Wearables', 'tablets-accessories': 'Tablets & Accessories',
    'video-games': 'Video Games', 'audio': 'Audio', 'photo-video': 'Photo & Video',
    'electronics': 'Electronics', 'telephony': 'Telephony', 'gadgets': 'Gadgets',
    'home-appliances': 'Home Appliances', 'tools': 'Tools', 'furniture': 'Furniture',
    'garden': 'Garden', 'home-items': 'Home Items', 'linens': 'Linens',
    'lighting': 'Lighting', 'kitchenware': 'Kitchenware', 'food-beverages': 'Food & Beverages',
    'electrical-supplies': 'Electrical Supplies', 'smoking-accessories': 'Smoking Accessories', 'office-supplies': 'Office Supplies',
    'gift-items': 'Gift Items', 'security-systems': 'Security Systems', 'professional-equipment': 'Professional Equipment',
    'seasonal-items': 'Seasonal Items', 'shopping-bags': 'Shopping Bags', 'shopping-trolleys': 'Shopping Trolleys',
    'church-items': 'Church Items', 'pet-supplies': 'Pet Supplies', 'womens-fashion': "Women's Fashion",
    'mens-fashion': "Men's Fashion", 'watches': 'Watches', 'jewelry': 'Jewelry',
    'eyewear': 'Eyewear', 'converse-all-star': 'Converse All Star', 'rain-umbrellas': 'Rain Umbrellas',
    'shoe-accessories': 'Shoe Accessories', 'kids-baby-fashion': "Kids & Baby Fashion", 'sneakers': 'Sneakers',
    'grooming': 'Grooming', 'pharmacy-products': 'Pharmacy Products', 'perfumes': 'Perfumes',
    'dietary-supplements': 'Dietary Supplements','grooming-devices': 'Grooming Devices', 'makeup': 'Makeup',
    'sunscreen-tanning': 'Sunscreen & Tanning', 'medical-supplies': 'Medical Supplies', 'manicure-pedicure': 'Manicure & Pedicure',
    'oral-hygiene': 'Oral Hygiene', 'sex-toys': 'Sex Toys', 'firming-slimming': 'Firming & Slimming',
    'cannabis-products': 'Cannabis Products', 'orthopedics': 'Orthopedics', 'patient-aids': 'Patient Aids',
    'optics': 'Optics', 'korean-cosmetics': 'Korean Cosmetics', 'kids-toys': "Kids' Toys",
    'school-supplies': 'School Supplies', 'baby-toys': 'Baby Toys', 'baby-items': 'Baby Items',
    'kids-linens': "Kids' Linens", 'christening-items': 'Christening Items', 'kids-watches': "Kids' Watches",
    'sports': 'Sports', 'cycling': 'Cycling', 'leisure-time': 'Leisure Time',
    'fishing-diving': 'Fishing & Diving', 'beach-sea-items': 'Beach & Sea Items', 'camping': 'Camping',
    'travel-items-bags': 'Travel Items & Bags', 'books': 'Books', 'hunting': 'Hunting',
    'fitness-equipment': 'Fitness Equipment', 'pet-supplies-hobby': 'Pet Supplies (Hobby)', 'drones-accessories': 'Drones & Accessories',
    'electric-scooters': 'Electric Scooters', 'hoverboards': 'Hoverboards', 'musical-instruments': 'Musical Instruments',
    'sports-accessories': 'Sports Accessories', 'exploration-items': 'Exploration Items',
    'womens-sportswear': "Women's Sportswear", 'womens-sports-shoes': "Women's Sports Shoes",
    'mens-sportswear': "Men's Sportswear", 'mens-sports-shoes': "Men's Sports Shoes",
    'car': 'Car', 'motorcycle': 'Motorcycle', 'boat': 'Boat',
    'truck-items': 'Truck Items', 'smartphones': 'Smartphones', 'iphone': 'iPhone',
    'mobile-cases': 'Mobile Cases', 'bluetooth-handsfree': 'Bluetooth Handsfree', 'handsfree': 'Handsfree',
    'mobile-chargers': 'Mobile Chargers', 'tempered-glass': 'Tempered Glass', 'screen-protectors': 'Screen Protectors',
    'power-banks': 'Power Banks', 'mobile-batteries': 'Mobile Batteries', 'selfie-sticks': 'Selfie Sticks',
    'mobile-holders': 'Mobile Holders', 'charging-data-cables': 'Charging & Data Cables', 'anti-lost-trackers': 'Anti-Lost Trackers',
    'mobile-spare-parts': 'Mobile Spare Parts', 'mobile-gimbals': 'Mobile Gimbals', 'stylus-pens': 'Stylus Pens',
    'stylus-accessories': 'Stylus Accessories', 'bluetooth-headset-accessories': 'Bluetooth Headset Accessories',
    'anti-lost-tracker-accessories': 'Anti-Lost Tracker Accessories',
    'pop-sockets': 'Pop Sockets', 'mobile-tripods': 'Mobile Tripods', 'mobile-service-tools': 'Mobile Service Tools',
    'mobile-charms': 'Mobile Charms', 'mobile-accessories': 'Mobile Accessories',
    'mobile-camera-protection': 'Mobile Camera Protection', 'mobile-camera-lenses': 'Mobile Camera Lenses',
    'mobile-signal-boosters': 'Mobile Signal Boosters', 'mobile-gaming-buttons': 'Mobile Gaming Buttons',
    'connection-packs': 'Connection Packs', 'portable-bluetooth-speakers-mobile': 'Portable Bluetooth Speakers (Mobile)',
    'ps5-games': 'PS5 Games', 'pc-games': 'PC Games', 'amplifiers-preamplifiers': 'Amplifiers & Preamplifiers',
    'hi-fi-systems': 'Hi-Fi Systems',
  },
  // ================================= Greek (el) ===================================
  el: {
    // This should be your fully translated Greek section
    email: 'Email', password: 'Κωδικός', forgotPassword: 'Ξεχάσατε τον κωδικό;', register: 'Εγγραφή',
    signIn: 'Σύνδεση', loggingIn: 'Γίνεται σύνδεση...', emailPlaceholder: 'email@example.com', orContinueWith: 'Ή συνεχίστε με',
    google: 'Google', facebook: 'Facebook', twitter: 'Twitter', createAccount: 'Δημιουργία Λογαριασμού',
    dontHaveAccount: 'Δεν έχετε λογαριασμό;', alreadyHaveAccount: 'Έχετε ήδη λογαριασμό;', fullName: 'Ονοματεπώνυμο', confirmPassword: 'Επαλήθευση Κωδικού',
    agreeToTerms: 'Συμφωνώ με τους Όρους Χρήσης και την Πολιτική Απορρήτου',
    creatingAccount: 'Δημιουργία Λογαριασμού...', resetYourPassword: 'Επαναφορά Κωδικού',
    enterEmailForReset: 'Εισαγάγετε το email σας και θα σας στείλουμε έναν σύνδεσμο για επαναφορά του κωδικού σας.',
    sendResetLink: 'Αποστολή Συνδέσμου', sendingResetLink: 'Αποστολή...',
    resetPasswordEmailSent: 'Το email επαναφοράς κωδικού στάλθηκε. Ελέγξτε τα εισερχόμενά σας.',
    backToLogin: 'Επιστροφή στη Σύνδεση', createNewPassword: 'Δημιουργία Νέου Κωδικού',
    newPassword: 'Νέος Κωδικός', updatePassword: 'Ενημέρωση Κωδικού',
    updating: 'Ενημέρωση...', passwordUpdated: 'Ο Κωδικός Ενημερώθηκε',
    passwordSuccessfullyChanged: 'Ο κωδικός σας άλλαξε επιτυχώς.',
    passwordResetFailed: 'Η Επαναφορά Κωδικού Απέτυχε',
    errorProcessingRequest: 'Παρουσιάστηκε σφάλμα κατά την επεξεργασία του αιτήματός σας.',
    passwordTooShort: 'Πολύ Κοντός Κωδικός', passwordMinLength: 'Ο κωδικός πρέπει να είναι τουλάχιστον 6 χαρακτήρες.',
    passwordsDontMatch: 'Οι Κωδικοί δεν Ταιριάζουν', pleaseCheckPasswords: 'Ελέγξτε ότι οι δύο κωδικοί ταιριάζουν.',
    languageSettings: 'Ρυθμίσεις Γλώσσας', selectLanguage: 'Επιλογή Γλώσσας', english: 'Αγγλικά', greek: 'Ελληνικά',
    spanish: 'Ισπανικά', french: 'Γαλλικά', german: 'Γερμανικά', systemLanguage: 'Γλώσσα Συστήματος (Προεπιλογή)',
    save: 'Αποθήκευση', cancel: 'Άκυρο', loading: 'Φόρτωση...', success: 'Επιτυχία',
    error: 'Σφάλμα', wallet: 'Πορτοφόλι', myWallet: 'Το Πορτοφόλι μου', manageWallet: 'Διαχείριση κεφαλαίων, συναλλαγών και διαφημίσεων',
    deposit: 'Κατάθεση', transactions: 'Συναλλαγές', connectWallet: 'Σύνδεση Πορτοφολιού', addFunds: 'Προσθήκη Χρημάτων',
    amount: 'Ποσό (€)', enterAmount: 'Εισάγετε ποσό', paymentMethod: 'Μέθοδος Πληρωμής', processing: 'Επεξεργασία...',
    myAccount: 'Ο Λογαριασμός μου', profile: 'Προφίλ', favorites: 'Αγαπημένα', recentlyViewed: 'Είδατε Πρόσφατα',
    priceAlerts: 'Ειδοποιήσεις Τιμών', settings: 'Ρυθμίσεις', logout: 'Αποσύνδεση', myProfile: 'Το Προφίλ μου',
    managePersonalInfo: 'Διαχείριση προσωπικών πληροφοριών',
    name: 'Όνομα', memberSince: 'Μέλος από', role: 'Ρόλος', administrator: 'Διαχειριστής',
    regularUser: 'Απλός Χρήστης', editProfile: 'Επεξεργασία Προφίλ', accountSummary: 'Σύνοψη Λογαριασμού', categories: 'Κατηγορίες',
    gifts: 'Δώρα', deals: 'Προσφορές', clearFilters: 'Καθαρισμός φίλτρων', finalPrice: 'Τελική τιμή',
    yes: "Ναι", no: "Όχι", ok: "OK", close: "Κλείσιμο",
    showMore: "Περισσότερα", showLess: "Λιγότερα", all: "Όλα", selectOption: "Επιλέξτε",
    optional: "Προαιρετικό", required: "Απαιτείται", back: "Πίσω", next: "Επόμενο",
    submit: "Υποβολή", search: "Αναζήτηση", searchPlaceholder: "Αναζήτηση προϊόντων...",
    notFoundPageTitle: "Η Σελίδα δεν Βρέθηκε", notFoundMessage: "Ουπς! Η σελίδα που αναζητάτε δεν υπάρχει.",
    recently_viewed_title: "Είδατε Πρόσφατα",
    "product_singular": "προϊόν", "product_plural": "{{count}} προϊόντα",
    "rating_label": "Βαθμολογία", "reviews_label_singular": "αξιολόγηση", "reviews_label_plural": "{{count}} αξιολογήσεις",
    "from_vendor": "από", "with": "με",
    "no_products_in_category": "Δεν υπάρχουν προϊόντα σε αυτή την κατηγορία ακόμα.",
    "filters_title": "Φίλτρα", "remove_all_filters_tooltip": "Αφαίρεση όλων των φίλτρων",
    "show_only_title": "Εμφάνιση μόνο", "deals_label": "Προσφορές",
    "deals_title": "Προϊόντα με σημαντική πτώση τιμής",
    "certified_label": "Πιστοποιημένα", "certified_stores_title": "Πιστοποιημένα Καταστήματα",
    "instock_label": "Διαθέσιμα", "instock_title": "Μόνο προϊόντα διαθέσιμα σε απόθεμα",
    "boxnow_delivery_title": "BOX NOW Παράδοση",
    "boxnow_tooltip": "Παραλάβετε την παραγγελία σας από ένα BOX NOW locker 24/7",
    "delivery_label": "BOX NOW", "manufacturer_title": "Κατασκευαστής",
    "show_less_manufacturers": "Λιγότεροι κατασκευαστές", "show_all_manufacturers": "Όλοι οι κατασκευαστές",
    "show_all": "Όλα",
    "show_less_options": "Λιγότερες επιλογές για", "show_all_options": "Όλες οι επιλογές για",
    "remove_instock_filter": "Αφαίρεση φίλτρου 'Διαθέσιμα'", "remove_deals_filter": "Αφαίρεση φίλτρου 'Προσφορές'",
    "remove_certified_filter": "Αφαίρεση φίλτρου 'Πιστοποιημένα'", "remove_nearby_filter": "Αφαίρεση φίλτρου 'Κοντινά'",
    "remove_boxnow_filter": "Αφαίρεση φίλτρου 'BOX NOW'",
    "remove_brand_filter": "Αφαίρεση φίλτρου κατασκευαστή", "remove_spec_filter": "Αφαίρεση φίλτρου χαρακτηριστικού",
    "reset_all_filters": "Επαναφορά όλων των φίλτρων", "clear_all_filters": "Καθαρισμός Όλων",
    "selected_deals": "Επιλεγμένες Προσφορές", "popular_choices": "Δημοφιλείς Επιλογές",
    "sort_most_popular": "Δημοφιλέστερα", "sort_newest": "Νεότερα",
    "sort_cheapest": "Φθηνότερα", "sort_most_expensive": "Ακριβότερα",
    "sort_alphabetical": "Αλφαβητικά (Α-Ω)", "sort_most_reviews": "Περισσότερες Αξιολογήσεις",
    "sort_by_manufacturer": " ανά Κατασκευαστή", "sort_num_stores": "Πλήθος Καταστημάτων",
    "price_alert_for": "Ειδοποίηση Τιμής για",
    "no_products_found_filters": "Κανένα προϊόν δεν αντιστοιχεί στα τρέχοντα φίλτρα σας.",
    "suggestions_title": "Προτάσεις",
    "suggestion_see_all_products": "Δείτε όλα τα προϊόντα αυτής της κατηγορίας:",
    "all_category_products": "Όλα τα Προϊόντα Κατηγορίας",
    "suggestion_try_removing_filters": "Δοκιμάστε να αφαιρέσετε μερικά φίλτρα:",
    "remove_a_filter": "Αφαίρεση φίλτρου",
    "suggestion_return_home": "Επιστρέψτε στην αρχική σελίδα:",
    "return_to_homepage": "Επιστροφή στην Αρχική",
    "no_subcategories": "Δεν υπάρχουν διαθέσιμες υποκατηγορίες.",
    "popular_categories": "Δημοφιλείς Κατηγορίες", "top_deals_in": "Top Προσφορές σε",
    "products_with_significant_price_drop": "Προϊόντα με σημαντική πτώση τιμής",
    "hottest_in": "Τα πιο Hot σε", "product_reviews_title": "Αξιολογήσεις Προϊόντων",
    "helpful_reviews_subtitle": "Χρήσιμες αξιολογήσεις από τους χρήστες μας",
    "popular_manufacturers": "Δημοφιλείς Κατασκευαστές",
    "price_alert_button": "Ειδοποίηση Πτώσης Τιμής",
    "price_alert_prompt_in": "Μην χάσετε ποτέ μια προσφορά για προϊόντα στην κατηγορία",
    "return_to": "Επιστροφή σε",
    "info_for_certified_store": "Πληροφορίες για πιστοποιημένο κατάστημα",
    "showing_products_from_store": "Εμφάνιση προϊόντων από το κατάστημα",
    "remove_filter": "Αφαίρεση αυτού του φίλτρου",
    "breadcrumbHome": "BestPrice",
    "breadcrumbAllProductsInCategory": "Όλα τα προϊόντα της κατηγορίας {{categoryName}}",
    "breadcrumbAllProductsAndSubcategoriesInCategory": "Όλα τα προϊόντα και οι υποκατηγορίες της κατηγορίας {{categoryName}}",
    "loadingProduct": "Φόρτωση Προϊόντος...",
    "addToShoppingList": "Προσθήκη στη Λίστα Αγορών", "addToComparison": "Προσθήκη στη σύγκριση",
    "iWantIt": "Το θέλω", "iHaveIt": "Το έχω",
    "notifyPriceDrop": "Ειδοποίηση για πτώση τιμής", "addToCollection": "Προσθήκη σε συλλογή",
    "priceFrom": "Από", "inStores": "σε {{count}} καταστήματα",
    "storesCount": "Καταστήματα ({{count}})",
    "available": "Διαθέσιμα", "nearMe": "Κοντά μου",
    "deliveryWithService": "Παράδοση με {{serviceName}}",
    "coupons": "Κουπόνια", "color": "Χρώμα",
    "officialResellers": "Επίσημοι μεταπωλητές", "priceHistoryTitle": "Ιστορικό Τιμών",
    "productDetails": "Λεπτομέρειες Προϊόντος", "userReviews": "Αξιολογήσεις Χρηστών ({{count}})",
    "questionsAndAnswers": "Ερωτήσεις & Απαντήσεις ({{count}})",
    "similarProducts": "Παρόμοια Προϊόντα", "dealsInCategory": "Προσφορές στην κατηγορία {{categoryName}}",
    "addToCart": "Προσθήκη στο Καλάθι", "buyNow": "Αγορά Τώρα",
    "specifications": "Χαρακτηριστικά", "reviews": "Αξιολογήσεις",
    "relatedProducts": "Σχετικά Προϊόντα", "writeReview": "Γράψτε Αξιολόγηση",
    "outOfStock": "Εξαντλημένο",
    "availableAt": "Διαθέσιμο σε {{count}} καταστήματα", "noStoresAvailable": "Προς το παρόν μη διαθέσιμο",
    "priceRange": "Εύρος Τιμών", "comparePrices": "Σύγκριση {{count}} Τιμών",
    "viewAllStores": "Δείτε όλα τα καταστήματα", "productDescription": "Περιγραφή",
    "share": "Κοινοποίηση", "removeFromFavorites": "Αφαίρεση από τα Αγαπημένα",
    "priceHistory": "Ιστορικό Τιμών",
    "certifiedStoresTooltip": "Εμφάνιση μόνο προϊόντων από πιστοποιημένα καταστήματα",
    "vendorPopupCertification": "Πιστοποίηση: {{certificationType}}",
    "vendorPopupInformation": "Πληροφορίες",
    "vendorPopupAddressNotAvailable": "Μόνο Ηλεκτρονικό κατάστημα",
    "vendorPopupPaymentMethods": "ΤΡΟΠΟΙ ΠΛΗΡΩΜΗΣ",
    "vendorPopupLearnMore": "Μάθε περισσότερα", "vendorPopupViewInStore": "Προβολή στο κατάστημα",
    "openingHoursNotAvailable": "Πληροφορίες ωραρίου μη διαθέσιμες",
    "closedToday": "Κλειστό σήμερα", "openUntil": "Ανοιχτό μέχρι τις {{time}}",
    "closedOpensAt": "Κλειστό - Ανοίγει στις {{time}}", "closedForToday": "Κλειστό για σήμερα",
    "openingHoursError": "Σφάλμα ωραρίου",
    "loginRequired": "Απαιτείται Σύνδεση",
    "loginToAddToFavorites": "Παρακαλώ συνδεθείτε για να προσθέσετε αυτό το προϊόν στα αγαπημένα σας",
    "productAddedToFavorites": "Το προϊόν {{productName}} προστέθηκε στα αγαπημένα",
    "linkCopied": "Ο Σύνδεσμος Αντιγράφηκε", "productLinkCopied": "Ο σύνδεσμος του προϊόντος αντιγράφηκε στο πρόχειρο",
    "copyFailed": "Η Αντιγραφή Απέτυχε", "couldNotCopyLink": " αδυναμία αντιγραφής συνδέσμου",
    "loginToSetPriceAlert": "Παρακαλώ συνδεθείτε για να ορίσετε ειδοποίηση τιμής",
    "loadingVendor": "Φόρτωση καταστήματος...", "allStores": "Καταστήματα",
    "certifiedStoreLinkText": "Πιστοποιημένο Κατάστημα ({{certificationLevel}})",
    "certifiedStoreFullText": "Το {{vendorName}} είναι πιστοποιημένο κατάστημα ({{certificationLevel}})",
    "memberSinceDate": "Στο BestPrice από {{date}}",
    "ratingTooltip": "{{rating}} αστέρια από {{count}} αξιολογήσεις",
    "social_facebook": "Facebook", "social_twitter": "Twitter", "social_instagram": "Instagram", "social_youtube": "YouTube", "social_linkedin": "LinkedIn", "social_tiktok": "TikTok",
    "additionalStores": "{{count}} ακόμη {{storeLabel}}",
    "storeLabelSingular": "κατάστημα", "storeLabelPlural": "καταστήματα",
    "logoFor": "Λογότυπο {{name}}", "screenshotFor": "Στιγμιότυπο {{name}}",
    "authorizedReseller": "Εξουσιοδοτημένος Μεταπωλητής", "previewWebsite": "Προεπισκόπηση Ιστοσελίδας",
    "dealsFromVendor": "Προσφορές από {{vendorName}}",
    "popularCategoriesInVendor": "Δημοφιλείς Κατηγορίες {{vendorName}}",
    "viewAllVendorProducts": "Δες όλα τα προϊόντα<span class=\"hide-mobile\"> του καταστήματος</span>",
    "storeReviewsTitle": "Αξιολογήσεις Καταστήματος {{vendorName}}",
    "reviewCount": "{{count}} αξιολογήσεις", "rateIt": "Αξιολόγησέ το",
    "reviewsPlaceholder": "(Προβολή αξιολογήσεων - Χρειάζεται Υλοποίηση)",
    "servicePointsTitle": "Σημεία Εξυπηρέτησης {{vendorName}}", "servicePointsCount": "{{count}} σημεία",
    "storeAndPickup": "Κατάστημα / Παραλαβή", "mapPlaceholderText": "Map Placeholder - Απαιτείται Βιβλιοθήκη Χάρτη",
    "noLanguagesInRegion": "Δεν υπάρχουν γλώσσες για αυτήν την περιοχή ακόμη.",
    "toggleTheme": "Εναλλαγή θέματος",
    "productsYouWant": "Προϊόντα που θέλεις", "productsYouHave": "Προϊόντα που έχεις",
    "myOffers": "Οι Προσφορές μου", "priceDrops": "Ειδοποιήσεις Τιμών",
    "myCollections": "Οι Συλλογές μου", "newCollection": "Νέα Συλλογή...",
    "creditsClub": "Credits Club", "savedOrders": "Αποθηκευμένες Παραγγελίες",
    "myQuestions": "Οι Ερωτήσεις μου", "myReviews": "Οι Αξιολογήσεις μου",
    "myFriends": "Οι Φίλοι μου", "viewProfileTooltip": "Δείτε το προφίλ σας",
    "userMenuCaretAlt": "Άνοιγμα μενού χρήστη",
    "backToTop": "Επιστροφή στην κορυφή",
    "bestpriceSloganShort": "Η πραγματικά καλύτερη τιμή",
    "bestpriceSloganLong": "Το BestPrice είναι η πρώτη και μεγαλύτερη υπηρεσία σύγκρισης τιμών στην Ελλάδα.",
    "bestpriceSloganFindDeals": "Στο BestPrice θα βρεις γρήγορα και εύκολα πραγματικές προσφορές και την καλύτερη τιμή από τα μεγαλύτερα καταστήματα.",
    "bestpriceGive": "BestPrice Give", "footerBestPriceSectionTitle": "BestPrice",
    "aboutUs": "Σχετικά με εμάς", "ourBlog": "Το Blog μας",
    "buyingGuides": "Οδηγοί αγοράς", "purchaseInsurance": "Ασφάλιση Αγορών",
    "advertising": "Διαφήμιση", "bestpriceCertification": "Πιστοποίηση BestPrice",
    "customerReviewAwards": "Customer Review Awards", "ourAwards": "Οι διακρίσεις μας",
    "ourTeam": "Η ομάδα μας", "bestpriceAssistant": "BestPrice Assistant",
    "jobOpenings": "Θέσεις εργασίας ({{count}})", "contactUs": "Επικοινωνία",
    "inNumbers": "Σε αριθμούς",
    "storeCountLink": "{{count}} καταστήματα", "productCountLink": "{{count}} προϊόντα",
    "brandCountLink": "{{count}} κατασκευαστές","dealCountLink": "{{count}} προσφορές",
    "termsAndPrivacy": "Όροι χρήσης & ιδιωτικότητα", "termsOfUse": "Όροι χρήσης",
    "privacyPolicy": "Πολιτική προσωπικών δεδομένων", "cookiePolicy": "Χρήση cookies",
    "gdprLink": "GDPR", "dsaLink": "DSA",
    "bestpriceForMerchants": "BestPrice For Merchants",
    "merchantsSectionSlogan1": "Έχεις ηλεκτρονικό κατάστημα;",
    "merchantsSectionSlogan2": "Δες πως το BestPrice μπορεί να σε βοηθήσει να αυξήσεις τις πωλήσεις σου!",
    "forMerchantsButton": "Για εμπόρους",
    "bestpriceForBrands": "BestPrice For Brands",
    "brandsSectionSlogan": "Το BestPrice for Brands θα προσφέρει χρήσιμες πληροφορίες & υπηρεσίες σε κατασκευαστές (Brands).",
    "moreInfoButton": "Περισσότερα",
    "bestpriceOnFacebook": "Το BestPrice στο Facebook", "bestpriceOnX": "Το BestPrice στο X",
    "bestpriceOnThreads": "Το BestPrice στο Threads", "bestpriceOnInstagram": "Το BestPrice στο Instagram",
    "bestpriceOnTikTok": "Το BestPrice στο TikTok", "bestpriceOnYouTube": "Το BestPrice στο YouTube",
    "bestpriceOnLinkedIn": "Το BestPrice στο LinkedIn",
    "homepageTitle": "Αρχική σελίδα",
    "changeLanguage": "Αλλαγή Γλώσσας", "selectYourLanguageTitle": "Επιλέξτε τη Γλώσσα σας",
    "suggestedLanguages": "Προτεινόμενες γλώσσες", "allLanguages": "Όλες οι γλώσσες",
    "languageCategoryEurope": "Ευρώπη", "languageCategoryAsia": "Ασία",
    "languageCategoryAmericas": "Αμερική", "languageCategoryAfrica": "Αφρική και Μέση Ανατολή",
    "languageCategoryEasternEurope": "Ανατολική Ευρώπη", "languageCategoryWesternEurope": "Δυτική Ευρώπη",
    "allBrands": "Όλες οι Μάρκες", "productsFromBrand": "Προϊόντα από {{brandName}}",
    "searchResultsFor": "Αποτελέσματα αναζήτησης για \"{{searchTerm}}\"",
    "noResultsFound": "Δεν βρέθηκαν αποτελέσματα για \"{{searchTerm}}\"",
    "sortBy": "Ταξινόμηση κατά", "viewAsGrid": "Προβολή Πλέγματος",
    "viewAsList": "Προβολή Λίστας", "itemsPerPage": "Αντικείμενα ανά σελίδα",
    "page": "Σελίδα", "of": "από", "nextPage": "Επόμενη", "previousPage": "Προηγούμενη",
    "todaysDeals": " σημερινές Προσφορές", "filterBy": "Φιλτράρισμα κατά",
    "shoppingCart": "Καλάθι Αγορών", "proceedToCheckout": "Ολοκλήρωση Παραγγελίας",
    "item": "Προϊόν", "quantity": "Ποσότητα", "subtotal": "Μερικό Σύνολο", "total": "Συνολικό Ποσό",
    "emptyCart": "Το καλάθι σας είναι άδειο.", "continueShopping": "Συνέχεια Αγορών",
    "shippingAddress": "Διεύθυνση Αποστολής", "billingAddress": "Διεύθυνση Χρέωσης",
    "paymentInformation": "Στοιχεία Πληρωμής", "placeOrder": "Καταχώρηση Παραγγελίας",
    "orderSummary": "Σύνοψη Παραγγελίας", "discountCode": "Κωδικός Έκπτωσης", "apply": "Εφαρμογή",
    "paymentMethod_credit_card": "Πιστωτική Κάρτα", "paymentMethod_bank_transfer": "Τραπεζική Κατάθεση",
    "paymentMethod_paypal": "PayPal", "paymentMethod_cash_on_delivery": "Αντικαταβολή",
    "paymentMethod_pickup_from_store": "Παραλαβή από το Κατάστημα", "paymentMethod_klarna": "Klarna",
    "paymentMethod_apple_pay": "Apple Pay", "paymentMethod_google_pay": "Google Pay",
    "paymentMethod_ideal": "iDEAL", "paymentMethod_crypto": "Κρυπτονόμισμα",
    "paymentMethod_pay_by_link": "Πληρωμή με Σύνδεσμο", "paymentMethod_pickup_via": "Παραλαβή μέσω Courier/Υπηρεσίας",
    'technology': 'Τεχνολογία', 'home-garden': 'Σπίτι & Κήπος', 'fashion': 'Μόδα',
    'health-beauty': 'Υγεία & Ομορφιά', 'kids-baby': 'Παιδικά - Βρεφικά', 'hobby-sports': 'Hobby, Αθλητισμός',
    'auto-moto': 'Μηχανοκίνηση',
    'mobile-telephony': 'Κινητή Τηλεφωνία', 'computers': 'Υπολογιστές', 'laptops-accessories': 'Laptops, Αξεσουάρ',
    'visual': 'Εικόνα', 'smartwatches-wearables': 'Smartwatches, Wearables', 'tablets-accessories': 'Tablets, Αξεσουάρ',
    'video-games': 'Video Games', 'audio': 'Ήχος', 'photo-video': 'Φωτογραφία, Video',
    'electronics': 'Ηλεκτρονικά', 'telephony': 'Τηλεφωνία', 'gadgets': 'Gadgets',
    'home-appliances': 'Οικιακές Συσκευές', 'tools': 'Εργαλεία', 'furniture': 'Έπιπλα',
    'garden': 'Κήπος', 'home-items': 'Είδη Σπιτιού', 'linens': 'Λευκά Είδη',
    'lighting': 'Φωτισμός', 'kitchenware': 'Είδη Κουζίνας', 'food-beverages': 'Τρόφιμα & Ποτά',
    'electrical-supplies': 'Ηλεκτρολογικά', 'smoking-accessories': 'Είδη Καπνιστού', 'office-supplies': 'Είδη Γραφείου',
    'gift-items': 'Είδη Δώρων', 'security-systems': 'Συστήματα Ασφαλείας', 'professional-equipment': 'Επαγγελματικός Εξοπλισμός',
    'seasonal-items': 'Εποχιακά Είδη', 'shopping-bags': 'Τσάντες για Ψώνια', 'shopping-trolleys': 'Καρότσια Λαϊκής',
    'church-items': 'Εκκλησιαστικά Είδη', 'pet-supplies': 'Είδη Κατοικιδίων', 'womens-fashion': 'Γυναικεία Μόδα',
    'mens-fashion': 'Ανδρική Μόδα', 'watches': 'Ρολόγια', 'jewelry': 'Κοσμήματα',
    'eyewear': 'Οπτικά', 'converse-all-star': 'Converse All Star', 'rain-umbrellas': 'Ομπρέλες Βροχής',
    'shoe-accessories': 'Αξεσουάρ Παπουτσιών', 'kids-baby-fashion': 'Παιδική, Βρεφική Μόδα', 'sneakers': 'Sneakers: Τα πιο trendy παπούτσια για κάθε στυλ και περίσταση!',
    'grooming': 'Περιποίηση', 'pharmacy-products': 'Είδη Φαρμακείου', 'perfumes': 'Αρώματα',
    'dietary-supplements': 'Συμπληρώματα Διατροφής','grooming-devices': 'Συσκευές Περιποίησης', 'makeup': 'Μακιγιάζ',
    'sunscreen-tanning': 'Αντηλιακή Προστασία, Μαύρισμα', 'medical-supplies': 'Ιατρικά Είδη', 'manicure-pedicure': 'Μανικιούρ - Πεντικιούρ',
    'oral-hygiene': 'Στοματική Υγιεινή', 'sex-toys': 'Sex Toys', 'firming-slimming': 'Σύσφιξη, Αδυνάτισμα',
    'cannabis-products': 'Προϊόντα Κάνναβης', 'orthopedics': 'Ορθοπεδικά', 'patient-aids': 'Βοηθήματα Ασθενών',
    'optics': 'Οπτικά', 'korean-cosmetics': 'Κορεάτικα Καλλυντικά', 'kids-toys': 'Παιδικά Παιχνίδια',
    'school-supplies': 'Σχολικά Είδη', 'baby-toys': 'Βρεφικά Παιχνίδια', 'baby-items': 'Βρεφικά Είδη',
    'kids-linens': 'Παιδικά Λευκά Είδη', 'christening-items': 'Βαπτιστικά', 'kids-watches': 'Παιδικά Ρολόγια',
    'sports': 'Αθλήματα', 'cycling': 'Ποδηλασία', 'leisure-time': 'Ελεύθερος Χρόνος',
    'fishing-diving': 'Ψάρεμα, Καταδύσεις', 'beach-sea-items': 'Είδη Θαλάσσης', 'camping': 'Camping',
    'travel-items-bags': 'Είδη Ταξιδίου, Τσάντες', 'books': 'Βιβλία', 'hunting': 'Κυνήγι',
    'fitness-equipment': 'Είδη Γυμναστικής', 'pet-supplies-hobby': 'Είδη Κατοικιδίων (Hobby)', 'drones-accessories': 'Drones & Αξεσουάρ',
    'electric-scooters': 'Ηλεκτρικά Πατίνια', 'hoverboards': 'Hoverboards', 'musical-instruments': 'Μουσικά Όργανα',
    'sports-accessories': 'Αξεσουάρ Αθλημάτων', 'exploration-items': 'Είδη Εξερεύνησης',
    'womens-sportswear': 'Γυναικεία Αθλητικά Ρούχα', 'womens-sports-shoes': 'Γυναικεία Αθλητικά Παπούτσια',
    'mens-sportswear': 'Ανδρικά Αθλητικά Ρούχα', 'mens-sports-shoes': 'Ανδρικά Αθλητικά Παπούτσια',
    'car': 'Αυτοκίνητο', 'motorcycle': 'Μοτοσυκλέτα', 'boat': 'Σκάφος',
    'truck-items': 'Είδη Φορτηγού', 'smartphones': 'Κινητά', 'iphone': 'iPhone',
    'mobile-cases': 'Θήκες Κινητών', 'bluetooth-handsfree': 'Bluetooth Handsfree', 'handsfree': 'Handsfree',
    'mobile-chargers': 'Φορτιστές Κινητών', 'tempered-glass': 'Tempered Glass', 'screen-protectors': 'Προστασία Οθόνης',
    'power-banks': 'Power Banks', 'mobile-batteries': 'Μπαταρίες Κινητών', 'selfie-sticks': 'Selfie Stick',
    'mobile-holders': 'Βάσεις Κινητού', 'charging-data-cables': 'Καλώδια Φόρτισης, Μεταφοράς Δεδομένων', 'anti-lost-trackers': 'Anti-Lost Tracker',
    'mobile-spare-parts': 'Ανταλλακτικά Κινητών', 'mobile-gimbals': 'Gimbal Κινητών', 'stylus-pens': 'Γραφίδες Αφής',
    'stylus-accessories': 'Αξεσουάρ Γραφίδας', 'bluetooth-headset-accessories': 'Αξεσουάρ Ακουστικών Bluetooth',
    'anti-lost-tracker-accessories': 'Αξεσουάρ Anti-Lost Tracker',
    'pop-sockets': 'Pop Sockets', 'mobile-tripods': 'Τρίποδα Κινητών', 'mobile-service-tools': 'Εργαλεία για Service Κινητών',
    'mobile-charms': 'Διακοσμητικά Κινητών', 'mobile-accessories': 'Αξεσουάρ Κινητών',
    'mobile-camera-protection': 'Προστασία Κάμερας Κινητών', 'mobile-camera-lenses': 'Φακοί Κάμερας Κινητών',
    'mobile-signal-boosters': 'Ενισχυτές Σήματος Κινητής Τηλεφωνίας', 'mobile-gaming-buttons': 'Πλήκτρα Mobile Gaming',
    'connection-packs': 'Πακέτα Σύνδεσης', 'portable-bluetooth-speakers-mobile': 'Φορητά Ηχεία Bluetooth',
    'ps5-games': 'PS5 Games', 'pc-games': 'PC Games', 'amplifiers-preamplifiers': 'Ενισχυτές, Προενισχυτές',
    'hi-fi-systems': 'Συστήματα Hi-Fi',
  },
  // ============================ Spanish (es) - Placeholder, needs full translation ============================
  es: {
    email: '[es] Email', password: '[es] Password', forgotPassword: '[es] Forgot Password?', register: '[es] Register',
    signIn: '[es] Sign In', loggingIn: '[es] Logging in...', emailPlaceholder: '[es] email@example.com', orContinueWith: '[es] Or continue with',
    google: '[es] Google', facebook: '[es] Facebook', twitter: '[es] Twitter', createAccount: '[es] Create Account',
    dontHaveAccount: "[es] Don't have an account?", alreadyHaveAccount: '[es] Already have an account?', fullName: '[es] Full Name', confirmPassword: '[es] Confirm Password',
    agreeToTerms: '[es] I agree to the Terms of Service and Privacy Policy',
    creatingAccount: '[es] Creating Account...', resetYourPassword: '[es] Reset Your Password',
    enterEmailForReset: '[es] Enter your email address and we will send you a link to reset your password.',
    sendResetLink: '[es] Send Reset Link', sendingResetLink: '[es] Sending...',
    resetPasswordEmailSent: '[es] Password reset email sent. Please check your inbox.',
    backToLogin: '[es] Back to Login', createNewPassword: '[es] Create New Password',
    newPassword: '[es] New Password', updatePassword: '[es] Update Password',
    updating: '[es] Updating...', passwordUpdated: '[es] Password Updated',
    passwordSuccessfullyChanged: '[es] Your password has been successfully changed.',
    passwordResetFailed: '[es] Password Reset Failed',
    errorProcessingRequest: '[es] There was an error processing your request.',
    passwordTooShort: '[es] Password Too Short', passwordMinLength: '[es] Password must be at least 6 characters.',
    passwordsDontMatch: '[es] Passwords Don\'t Match', pleaseCheckPasswords: '[es] Please check that both passwords match.',
    languageSettings: '[es] Language Settings', selectLanguage: '[es] Select Language', english: '[es] English', greek: '[es] Greek',
    spanish: '[es] Spanish', french: '[es] French', german: '[es] German', systemLanguage: '[es] System Language (Default)',
    save: '[es] Save', cancel: '[es] Cancel', loading: '[es] Loading...', success: '[es] Success',
    error: '[es] Error', wallet: '[es] Wallet', myWallet: '[es] My Wallet', manageWallet: '[es] Manage your funds, transactions, and ad payments',
    deposit: '[es] Deposit', transactions: '[es] Transactions', connectWallet: '[es] Connect Wallet', addFunds: '[es] Add Funds',
    amount: '[es] Amount ($)', enterAmount: '[es] Enter amount', paymentMethod: '[es] Payment Method', processing: '[es] Processing...',
    myAccount: '[es] My Account', profile: '[es] Profile', favorites: '[es] Favorites', recentlyViewed: '[es] Recently Viewed',
    priceAlerts: '[es] Price Alerts', settings: '[es] Settings', logout: '[es] Logout', myProfile: '[es] My Profile',
    managePersonalInfo: '[es] Manage your personal information',
    name: '[es] Name', memberSince: '[es] Member since', role: '[es] Role', administrator: '[es] Administrator',
    regularUser: '[es] Regular User', editProfile: '[es] Edit Profile', accountSummary: '[es] Account Summary', categories: '[es] Categories',
    gifts: '[es] Gifts', deals: '[es] Deals', clearFilters: '[es] Clear filters', finalPrice: '[es] Final price',
    yes: "[es] Yes", no: "[es] No", ok: "[es] OK", close: "[es] Close",
    showMore: "[es] Show More", showLess: "[es] Show Less", all: "[es] All", selectOption: "[es] Select an option",
    optional: "[es] Optional", required: "[es] Required", back: "[es] Back", next: "[es] Next",
    submit: "[es] Submit", search: "[es] Search", searchPlaceholder: "[es] Search for products...",
    notFoundPageTitle: "[es] Page Not Found", notFoundMessage: "[es] Oops! The page you are looking for does not exist.",
    recently_viewed_title: "[es] Recently Viewed",
    "product_singular": "[es] product", "product_plural": "{{count}} [es] products",
    "rating_label": "[es] Rating", "reviews_label_singular": "[es] review", "reviews_label_plural": "{{count}} [es] reviews",
    "from_vendor": "[es] from", "with": "[es] with",
    "no_products_in_category": "[es] There are no products in this category yet.",
    "filters_title": "[es] Filters", "remove_all_filters_tooltip": "[es] Remove all filters",
    "show_only_title": "[es] Show only", "deals_label": "[es] Deals",
    "deals_title": "[es] Products with significant price drop",
    "certified_label": "[es] Certified", "certified_stores_title": "[es] Certified Stores",
    "instock_label": "[es] In Stock", "instock_title": "[es] Only products available in stock",
    "boxnow_delivery_title": "[es] BOX NOW Delivery",
    "boxnow_tooltip": "[es] Pick up your order from a BOX NOW locker 24/7",
    "delivery_label": "[es] BOX NOW", "manufacturer_title": "[es] Manufacturer",
    "show_less_manufacturers": "[es] Show less manufacturers", "show_all_manufacturers": "[es] Show all manufacturers",
    "show_all": "[es] Show All",
    "show_less_options": "[es] Show less options for", "show_all_options": "[es] Show all options for",
    "remove_instock_filter": "[es] Remove 'In Stock' filter", "remove_deals_filter": "[es] Remove 'Deals' filter",
    "remove_certified_filter": "[es] Remove 'Certified' filter", "remove_nearby_filter": "[es] Remove 'Nearby' filter",
    "remove_boxnow_filter": "[es] Remove 'BOX NOW' filter",
    "remove_brand_filter": "[es] Remove brand filter", "remove_spec_filter": "[es] Remove spec filter",
    "reset_all_filters": "[es] Reset all filters", "clear_all_filters": "[es] Clear All",
    "selected_deals": "[es] Selected Deals", "popular_choices": "[es] Popular Choices",
    "sort_most_popular": "[es] Most Popular", "sort_newest": "[es] Newest",
    "sort_cheapest": "[es] Cheapest", "sort_most_expensive": "[es] Most Expensive",
    "sort_alphabetical": "[es] Alphabetical (A-Z)", "sort_most_reviews": "[es] Most Reviews",
    "sort_by_manufacturer": "[es] By Manufacturer", "sort_num_stores": "[es] Number of Stores",
    "price_alert_for": "[es] Price Alert for",
    "no_products_found_filters": "[es] No products match your current filters.",
    "suggestions_title": "[es] Suggestions",
    "suggestion_see_all_products": "[es] See all products in this category:",
    "all_category_products": "[es] All Category Products",
    "suggestion_try_removing_filters": "[es] Try removing some filters:",
    "remove_a_filter": "[es] Remove a filter",
    "suggestion_return_home": "[es] Return to the homepage:",
    "return_to_homepage": "[es] Return to Homepage",
    "no_subcategories": "[es] No subcategories available.",
    "popular_categories": "[es] Popular Categories", "top_deals_in": "[es] Top Deals in",
    "products_with_significant_price_drop": "[es] Products with a significant price drop",
    "hottest_in": "[es] Hottest in", "product_reviews_title": "[es] Product Reviews",
    "helpful_reviews_subtitle": "[es] Helpful reviews from our users",
    "popular_manufacturers": "[es] Popular Manufacturers",
    "price_alert_button": "[es] Set Price Alert",
    "price_alert_prompt_in": "[es] Never miss a deal for products in",
    "return_to": "[es] Return to",
    "info_for_certified_store": "[es] Information for certified store",
    "showing_products_from_store": "[es] Showing products from store",
    "remove_filter": "[es] Remove this filter",
    "breadcrumbHome": "[es] BestPrice",
    "breadcrumbAllProductsInCategory": "[es] All products in the {{categoryName}} category",
    "breadcrumbAllProductsAndSubcategoriesInCategory": "[es] All products and subcategories in the {{categoryName}} category",
    "loadingProduct": "[es] Loading Product...",
    "addToShoppingList": "[es] Add to Shopping List", "addToComparison": "[es] Add to Comparison",
    "iWantIt": "[es] I Want It", "iHaveIt": "[es] I Have It",
    "notifyPriceDrop": "[es] Notify for Price Drop", "addToCollection": "[es] Add to Collection",
    "priceFrom": "[es] From", "inStores": "[es] in {{count}} stores",
    "storesCount": "[es] Stores ({{count}})",
    "available": "[es] Available", "nearMe": "[es] Near Me",
    "deliveryWithService": "[es] Delivery with {{serviceName}}",
    "coupons": "[es] Coupons", "color": "[es] Color",
    "officialResellers": "[es] Official Resellers", "priceHistoryTitle": "[es] Price History",
    "productDetails": "[es] Product Details", "userReviews": "[es] User Reviews ({{count}})",
    "questionsAndAnswers": "[es] Questions & Answers ({{count}})",
    "similarProducts": "[es] Similar Products", "dealsInCategory": "[es] Deals in {{categoryName}}",
    "addToCart": "[es] Add to Cart", "buyNow": "[es] Buy Now",
    "specifications": "[es] Specifications", "reviews": "[es] Reviews",
    "relatedProducts": "[es] Related Products", "writeReview": "[es] Write a Review",
    "outOfStock": "[es] Out of Stock",
    "availableAt": "[es] Available at {{count}} stores", "noStoresAvailable": "[es] Currently unavailable",
    "priceRange": "[es] Price Range", "comparePrices": "[es] Compare {{count}} Prices",
    "viewAllStores": "[es] View all stores", "productDescription": "[es] Description",
    "share": "[es] Share", "removeFromFavorites": "[es] Remove from Favorites",
    "priceHistory": "[es] Price History",
    "certifiedStoresTooltip": "[es] Show only products from certified stores",
    "vendorPopupCertification": "[es] Certification: {{certificationType}}",
    "vendorPopupInformation": "[es] Information",
    "vendorPopupAddressNotAvailable": "[es] Online Only Store",
    "vendorPopupPaymentMethods": "[es] PAYMENT METHODS",
    "vendorPopupLearnMore": "[es] Learn More", "vendorPopupViewInStore": "[es] View in Store",
    "openingHoursNotAvailable": "[es] Opening hours information not available",
    "closedToday": "[es] Closed today", "openUntil": "[es] Open until {{time}}",
    "closedOpensAt": "[es] Closed - Opens at {{time}}", "closedForToday": "[es] Closed for today",
    "openingHoursError": "[es] Error in opening hours",
    "loginRequired": "[es] Login Required",
    "loginToAddToFavorites": "[es] Please log in to add this product to your favorites",
    "productAddedToFavorites": "{{productName}} [es] has been added to your favorites",
    "linkCopied": "[es] Link Copied", "productLinkCopied": "[es] Product link copied to clipboard",
    "copyFailed": "[es] Copy Failed", "couldNotCopyLink": "[es] Could not copy link",
    "loginToSetPriceAlert": "[es] Please log in to set a price alert",
    "loadingVendor": "[es] Loading store...", "allStores": "[es] Stores",
    "certifiedStoreLinkText": "[es] Certified Store ({{certificationLevel}})",
    "certifiedStoreFullText": "{{vendorName}} [es] is a certified store ({{certificationLevel}})",
    "memberSinceDate": "[es] On BestPrice since {{date}}",
    "ratingTooltip": "{{rating}} [es] stars from {{count}} ratings",
    "social_facebook": "[es] Facebook", "social_twitter": "[es] Twitter", "social_instagram": "[es] Instagram", "social_youtube": "[es] YouTube", "social_linkedin": "[es] LinkedIn", "social_tiktok": "[es] TikTok",
    "additionalStores": "{{count}} [es] more {{storeLabel}}",
    "storeLabelSingular": "[es] store", "storeLabelPlural": "[es] stores",
    "logoFor": "{{name}} [es] logo", "screenshotFor": "{{name}} [es] Screenshot",
    "authorizedReseller": "[es] Authorized Reseller", "previewWebsite": "[es] Preview Website",
    "dealsFromVendor": "[es] Deals from {{vendorName}}",
    "popularCategoriesInVendor": "[es] Popular Categories in {{vendorName}}",
    "viewAllVendorProducts": "[es] View all products<span class=\"hide-mobile\"> of the store</span>",
    "storeReviewsTitle": "[es] Store Reviews for {{vendorName}}",
    "reviewCount": "{{count}} [es] reviews", "rateIt": "[es] Rate It",
    "reviewsPlaceholder": "[es] (Reviews display - Implementation needed)",
    "servicePointsTitle": "[es] Service Points for {{vendorName}}",
    "servicePointsCount": "{{count}} [es] points",
    "storeAndPickup": "[es] Store / Pickup Point",
    "mapPlaceholderText": "[es] Map Placeholder - Requires Map Library",
    "noLanguagesInRegion": "[es] No languages listed for this region yet.",
    "toggleTheme": "[es] Toggle theme",
    "productsYouWant": "[es] Products you want", "productsYouHave": "[es] Products you have",
    "myOffers": "[es] My Offers", "priceDrops": "[es] Price Drops",
    "myCollections": "[es] My Collections", "newCollection": "[es] New Collection...",
    "creditsClub": "[es] Credits Club", "savedOrders": "[es] Saved Orders",
    "myQuestions": "[es] My Questions", "myReviews": "[es] My Reviews",
    "myFriends": "[es] My Friends", "viewProfileTooltip": "[es] View your profile",
    "userMenuCaretAlt": "[es] Open user menu",
    "backToTop": "[es] Back to Top",
    "bestpriceSloganShort": "[es] The truly best price",
    "bestpriceSloganLong": "[es] BestPrice is the first and largest price comparison service in Greece.",
    "bestpriceSloganFindDeals": "[es] At BestPrice you will quickly and easily find real offers and the best price from the largest stores.",
    "bestpriceGive": "[es] BestPrice Give", "footerBestPriceSectionTitle": "[es] BestPrice",
    "aboutUs": "[es] About Us", "ourBlog": "[es] Our Blog",
    "buyingGuides": "[es] Buying Guides", "purchaseInsurance": "[es] Purchase Insurance",
    "advertising": "[es] Advertising", "bestpriceCertification": "[es] BestPrice Certification",
    "customerReviewAwards": "[es] Customer Review Awards", "ourAwards": "[es] Our Awards",
    "ourTeam": "[es] Our Team", "bestpriceAssistant": "[es] BestPrice Assistant",
    "jobOpenings": "[es] Job Openings ({{count}})", "contactUs": "[es] Contact",
    "inNumbers": "[es] In Numbers",
    "storeCountLink": "{{count}} [es] stores", "productCountLink": "{{count}} [es] products",
    "brandCountLink": "{{count}} [es] manufacturers","dealCountLink": "{{count}} [es] offers",
    "termsAndPrivacy": "[es] Terms & Privacy", "termsOfUse": "[es] Terms of Use",
    "privacyPolicy": "[es] Privacy Policy", "cookiePolicy": "[es] Cookie Policy",
    "gdprLink": "[es] GDPR", "dsaLink": "[es] DSA",
    "bestpriceForMerchants": "[es] BestPrice For Merchants",
    "merchantsSectionSlogan1": "[es] Do you have an online store?",
    "merchantsSectionSlogan2": "[es] See how BestPrice can help you increase your sales!",
    "forMerchantsButton": "[es] For Merchants",
    "bestpriceForBrands": "[es] BestPrice For Brands",
    "brandsSectionSlogan": "[es] BestPrice for Brands will offer useful information & services to manufacturers (Brands).",
    "moreInfoButton": "[es] More Info",
    "bestpriceOnFacebook": "[es] BestPrice on Facebook", "bestpriceOnX": "[es] BestPrice on X",
    "bestpriceOnThreads": "[es] BestPrice on Threads", "bestpriceOnInstagram": "[es] BestPrice on Instagram",
    "bestpriceOnTikTok": "[es] BestPrice on TikTok", "bestpriceOnYouTube": "[es] BestPrice on YouTube",
    "bestpriceOnLinkedIn": "[es] BestPrice on LinkedIn",
    "homepageTitle": "[es] Homepage",
    "changeLanguage": "[es] Change Language", "selectYourLanguageTitle": "[es] Select Your Language",
    "suggestedLanguages": "[es] Suggested Languages", "allLanguages": "[es] All Languages",
    "languageCategoryEurope": "[es] Europe", "languageCategoryAsia": "[es] Asia",
    "languageCategoryAmericas": "[es] Americas", "languageCategoryAfrica": "[es] Africa & Middle East",
    "languageCategoryEasternEurope": "[es] Eastern Europe", "languageCategoryWesternEurope": "[es] Western Europe",
    "allBrands": "[es] All Brands", "productsFromBrand": "[es] Products from {{brandName}}",
    "searchResultsFor": "[es] Search results for \"{{searchTerm}}\"",
    "noResultsFound": "[es] No results found for \"{{searchTerm}}\"",
    "sortBy": "[es] Sort by", "viewAsGrid": "[es] Grid View",
    "viewAsList": "[es] List View", "itemsPerPage": "[es] Items per page",
    "page": "[es] Page", "of": "[es] of", "nextPage": "[es] Next", "previousPage": "[es] Previous",
    "todaysDeals": "[es] Today's Deals", "filterBy": "[es] Filter by",
    "shoppingCart": "[es] Shopping Cart", "proceedToCheckout": "[es] Proceed to Checkout",
    "item": "[es] Item", "quantity": "[es] Quantity", "subtotal": "[es] Subtotal", "total": "[es] Total",
    "emptyCart": "[es] Your cart is empty.", "continueShopping": "[es] Continue Shopping",
    "shippingAddress": "[es] Shipping Address", "billingAddress": "[es] Billing Address",
    "paymentInformation": "[es] Payment Information", "placeOrder": "[es] Place Order",
    "orderSummary": "[es] Order Summary", "discountCode": "[es] Discount Code", "apply": "[es] Apply",
    "paymentMethod_credit_card": "[es] Credit Card", "paymentMethod_bank_transfer": "[es] Bank Transfer",
    "paymentMethod_paypal": "[es] PayPal", "paymentMethod_cash_on_delivery": "[es] Cash on Delivery",
    "paymentMethod_pickup_from_store": "[es] Pickup from Store", "paymentMethod_klarna": "[es] Klarna",
    "paymentMethod_apple_pay": "[es] Apple Pay", "paymentMethod_google_pay": "[es] Google Pay",
    "paymentMethod_ideal": "[es] iDEAL", "paymentMethod_crypto": "[es] Cryptocurrency",
    "paymentMethod_pay_by_link": "[es] Pay by Link", "paymentMethod_pickup_via": "[es] Pickup via Courier/Service",
    'technology': '[es] Technology', 'home-garden': '[es] Home & Garden', 'fashion': '[es] Fashion', 
    'health-beauty': '[es] Health & Beauty', 'kids-baby': '[es] Kids & Baby', 'hobby-sports': '[es] Hobby & Sports',
    'auto-moto': '[es] Auto & Moto',
    'mobile-telephony': '[es] Mobile Telephony', 'computers': '[es] Computers', 'laptops-accessories': '[es] Laptops & Accessories',
    'visual': '[es] Visual', 'smartwatches-wearables': '[es] Smartwatches & Wearables', 'tablets-accessories': '[es] Tablets & Accessories',
    'video-games': '[es] Video Games', 'audio': '[es] Audio', 'photo-video': '[es] Photo & Video',
    'electronics': '[es] Electronics', 'telephony': '[es] Telephony', 'gadgets': '[es] Gadgets',
    'home-appliances': '[es] Home Appliances', 'tools': '[es] Tools', 'furniture': '[es] Furniture',
    'garden': '[es] Garden', 'home-items': '[es] Home Items', 'linens': '[es] Linens',
    'lighting': '[es] Lighting', 'kitchenware': '[es] Kitchenware', 'food-beverages': '[es] Food & Beverages',
    'electrical-supplies': '[es] Electrical Supplies', 'smoking-accessories': '[es] Smoking Accessories', 'office-supplies': '[es] Office Supplies',
    'gift-items': '[es] Gift Items', 'security-systems': '[es] Security Systems', 'professional-equipment': '[es] Professional Equipment',
    'seasonal-items': '[es] Seasonal Items', 'shopping-bags': '[es] Shopping Bags', 'shopping-trolleys': '[es] Shopping Trolleys',
    'church-items': '[es] Church Items', 'pet-supplies': '[es] Pet Supplies', 'womens-fashion': "[es] Women's Fashion",
    'mens-fashion': "[es] Men's Fashion", 'watches': '[es] Watches', 'jewelry': '[es] Jewelry',
    'eyewear': '[es] Eyewear', 'converse-all-star': '[es] Converse All Star', 'rain-umbrellas': '[es] Rain Umbrellas',
    'shoe-accessories': '[es] Shoe Accessories', 'kids-baby-fashion': "[es] Kids & Baby Fashion", 'sneakers': '[es] Sneakers',
    'grooming': '[es] Grooming', 'pharmacy-products': '[es] Pharmacy Products', 'perfumes': '[es] Perfumes',
    'dietary-supplements': '[es] Dietary Supplements','grooming-devices': '[es] Grooming Devices', 'makeup': '[es] Makeup',
    'sunscreen-tanning': '[es] Sunscreen & Tanning', 'medical-supplies': '[es] Medical Supplies', 'manicure-pedicure': '[es] Manicure & Pedicure',
    'oral-hygiene': '[es] Oral Hygiene', 'sex-toys': '[es] Sex Toys', 'firming-slimming': '[es] Firming & Slimming',
    'cannabis-products': '[es] Cannabis Products', 'orthopedics': '[es] Orthopedics', 'patient-aids': '[es] Patient Aids',
    'optics': '[es] Optics', 'korean-cosmetics': '[es] Korean Cosmetics', 'kids-toys': "[es] Kids' Toys",
    'school-supplies': '[es] School Supplies', 'baby-toys': '[es] Baby Toys', 'baby-items': '[es] Baby Items',
    'kids-linens': "[es] Kids' Linens", 'christening-items': '[es] Christening Items', 'kids-watches': "[es] Kids' Watches",
    'sports': '[es] Sports', 'cycling': '[es] Cycling', 'leisure-time': '[es] Leisure Time',
    'fishing-diving': '[es] Fishing & Diving', 'beach-sea-items': '[es] Beach & Sea Items', 'camping': '[es] Camping',
    'travel-items-bags': '[es] Travel Items & Bags', 'books': '[es] Books', 'hunting': '[es] Hunting',
    'fitness-equipment': '[es] Fitness Equipment', 'pet-supplies-hobby': '[es] Pet Supplies (Hobby)', 'drones-accessories': '[es] Drones & Accessories',
    'electric-scooters': '[es] Electric Scooters', 'hoverboards': '[es] Hoverboards', 'musical-instruments': '[es] Musical Instruments',
    'sports-accessories': '[es] Sports Accessories', 'exploration-items': '[es] Exploration Items',
    'womens-sportswear': "[es] Women's Sportswear", 'womens-sports-shoes': "[es] Women's Sports Shoes",
    'mens-sportswear': "[es] Men's Sportswear", 'mens-sports-shoes': "[es] Men's Sports Shoes",
    'car': '[es] Car', 'motorcycle': '[es] Motorcycle', 'boat': '[es] Boat',
    'truck-items': '[es] Truck Items', 'smartphones': '[es] Smartphones', 'iphone': '[es] iPhone',
    'mobile-cases': '[es] Mobile Cases', 'bluetooth-handsfree': '[es] Bluetooth Handsfree', 'handsfree': '[es] Handsfree',
    'mobile-chargers': '[es] Mobile Chargers', 'tempered-glass': '[es] Tempered Glass', 'screen-protectors': '[es] Screen Protectors',
    'power-banks': '[es] Power Banks', 'mobile-batteries': '[es] Mobile Batteries', 'selfie-sticks': '[es] Selfie Sticks',
    'mobile-holders': '[es] Mobile Holders', 'charging-data-cables': '[es] Charging & Data Cables', 'anti-lost-trackers': '[es] Anti-Lost Trackers',
    'mobile-spare-parts': '[es] Mobile Spare Parts', 'mobile-gimbals': '[es] Mobile Gimbals', 'stylus-pens': '[es] Stylus Pens',
    'stylus-accessories': '[es] Stylus Accessories', 'bluetooth-headset-accessories': '[es] Bluetooth Headset Accessories',
    'anti-lost-tracker-accessories': '[es] Anti-Lost Tracker Accessories',
    'pop-sockets': '[es] Pop Sockets', 'mobile-tripods': '[es] Mobile Tripods', 'mobile-service-tools': '[es] Mobile Service Tools',
    'mobile-charms': '[es] Mobile Charms', 'mobile-accessories': '[es] Mobile Accessories',
    'mobile-camera-protection': '[es] Mobile Camera Protection', 'mobile-camera-lenses': '[es] Mobile Camera Lenses',
    'mobile-signal-boosters': '[es] Mobile Signal Boosters', 'mobile-gaming-buttons': '[es] Mobile Gaming Buttons',
    'connection-packs': '[es] Connection Packs', 'portable-bluetooth-speakers-mobile': '[es] Portable Bluetooth Speakers (Mobile)',
    'ps5-games': '[es] PS5 Games', 'pc-games': '[es] PC Games', 'amplifiers-preamplifiers': '[es] Amplifiers & Preamplifiers',
    'hi-fi-systems': '[es] Hi-Fi Systems',
  },
  // ============================ French (fr) - Placeholder, needs full translation =============================
  fr: {
    email: '[fr] Email', password: '[fr] Password', forgotPassword: '[fr] Forgot Password?', register: '[fr] Register',
    signIn: '[fr] Sign In', loggingIn: '[fr] Logging in...', emailPlaceholder: '[fr] email@example.com', orContinueWith: '[fr] Or continue with',
    google: '[fr] Google', facebook: '[fr] Facebook', twitter: '[fr] Twitter', createAccount: '[fr] Create Account',
    dontHaveAccount: "[fr] Don't have an account?", alreadyHaveAccount: '[fr] Already have an account?', fullName: '[fr] Full Name', confirmPassword: '[fr] Confirm Password',
    agreeToTerms: '[fr] I agree to the Terms of Service and Privacy Policy',
    creatingAccount: '[fr] Creating Account...', resetYourPassword: '[fr] Reset Your Password',
    enterEmailForReset: '[fr] Enter your email address and we will send you a link to reset your password.',
    sendResetLink: '[fr] Send Reset Link', sendingResetLink: '[fr] Sending...',
    resetPasswordEmailSent: '[fr] Password reset email sent. Please check your inbox.',
    backToLogin: '[fr] Back to Login', createNewPassword: '[fr] Create New Password',
    newPassword: '[fr] New Password', updatePassword: '[fr] Update Password',
    updating: '[fr] Updating...', passwordUpdated: '[fr] Password Updated',
    passwordSuccessfullyChanged: '[fr] Your password has been successfully changed.',
    passwordResetFailed: '[fr] Password Reset Failed',
    errorProcessingRequest: '[fr] There was an error processing your request.',
    passwordTooShort: '[fr] Password Too Short', passwordMinLength: '[fr] Password must be at least 6 characters.',
    passwordsDontMatch: '[fr] Passwords Don\'t Match', pleaseCheckPasswords: '[fr] Please check that both passwords match.',
    languageSettings: '[fr] Language Settings', selectLanguage: '[fr] Select Language', english: '[fr] English', greek: '[fr] Greek',
    spanish: '[fr] Spanish', french: '[fr] French', german: '[fr] German', systemLanguage: '[fr] System Language (Default)',
    save: '[fr] Save', cancel: '[fr] Cancel', loading: '[fr] Loading...', success: '[fr] Success',
    error: '[fr] Error', wallet: '[fr] Wallet', myWallet: '[fr] My Wallet', manageWallet: '[fr] Manage your funds, transactions, and ad payments',
    deposit: '[fr] Deposit', transactions: '[fr] Transactions', connectWallet: '[fr] Connect Wallet', addFunds: '[fr] Add Funds',
    amount: '[fr] Amount ($)', enterAmount: '[fr] Enter amount', paymentMethod: '[fr] Payment Method', processing: '[fr] Processing...',
    myAccount: '[fr] My Account', profile: '[fr] Profile', favorites: '[fr] Favorites', recentlyViewed: '[fr] Recently Viewed',
    priceAlerts: '[fr] Price Alerts', settings: '[fr] Settings', logout: '[fr] Logout', myProfile: '[fr] My Profile',
    managePersonalInfo: '[fr] Manage your personal information',
    name: '[fr] Name', memberSince: '[fr] Member since', role: '[fr] Role', administrator: '[fr] Administrator',
    regularUser: '[fr] Regular User', editProfile: '[fr] Edit Profile', accountSummary: '[fr] Account Summary', categories: '[fr] Categories',
    gifts: '[fr] Gifts', deals: '[fr] Deals', clearFilters: '[fr] Clear filters', finalPrice: '[fr] Final price',
    yes: "[fr] Yes", no: "[fr] No", ok: "[fr] OK", close: "[fr] Close",
    showMore: "[fr] Show More", showLess: "[fr] Show Less", all: "[fr] All", selectOption: "[fr] Select an option",
    optional: "[fr] Optional", required: "[fr] Required", back: "[fr] Back", next: "[fr] Next",
    submit: "[fr] Submit", search: "[fr] Search", searchPlaceholder: "[fr] Search for products...",
    notFoundPageTitle: "[fr] Page Not Found", notFoundMessage: "[fr] Oops! The page you are looking for does not exist.",
    recently_viewed_title: "[fr] Recently Viewed",
    "product_singular": "[fr] product", "product_plural": "{{count}} [fr] products",
    "rating_label": "[fr] Rating", "reviews_label_singular": "[fr] review", "reviews_label_plural": "{{count}} [fr] reviews",
    "from_vendor": "[fr] from", "with": "[fr] with",
    "no_products_in_category": "[fr] There are no products in this category yet.",
    "filters_title": "[fr] Filters", "remove_all_filters_tooltip": "[fr] Remove all filters",
    "show_only_title": "[fr] Show only", "deals_label": "[fr] Deals",
    "deals_title": "[fr] Products with significant price drop",
    "certified_label": "[fr] Certified", "certified_stores_title": "[fr] Certified Stores",
    "instock_label": "[fr] In Stock", "instock_title": "[fr] Only products available in stock",
    "boxnow_delivery_title": "[fr] BOX NOW Delivery",
    "boxnow_tooltip": "[fr] Pick up your order from a BOX NOW locker 24/7",
    "delivery_label": "[fr] BOX NOW", "manufacturer_title": "[fr] Manufacturer",
    "show_less_manufacturers": "[fr] Show less manufacturers", "show_all_manufacturers": "[fr] Show all manufacturers",
    "show_all": "[fr] Show All",
    "show_less_options": "[fr] Show less options for", "show_all_options": "[fr] Show all options for",
    "remove_instock_filter": "[fr] Remove 'In Stock' filter", "remove_deals_filter": "[fr] Remove 'Deals' filter",
    "remove_certified_filter": "[fr] Remove 'Certified' filter", "remove_nearby_filter": "[fr] Remove 'Nearby' filter",
    "remove_boxnow_filter": "[fr] Remove 'BOX NOW' filter",
    "remove_brand_filter": "[fr] Remove brand filter", "remove_spec_filter": "[fr] Remove spec filter",
    "reset_all_filters": "[fr] Reset all filters", "clear_all_filters": "[fr] Clear All",
    "selected_deals": "[fr] Selected Deals", "popular_choices": "[fr] Popular Choices",
    "sort_most_popular": "[fr] Most Popular", "sort_newest": "[fr] Newest",
    "sort_cheapest": "[fr] Cheapest", "sort_most_expensive": "[fr] Most Expensive",
    "sort_alphabetical": "[fr] Alphabetical (A-Z)", "sort_most_reviews": "[fr] Most Reviews",
    "sort_by_manufacturer": "[fr] By Manufacturer", "sort_num_stores": "[fr] Number of Stores",
    "price_alert_for": "[fr] Price Alert for",
    "no_products_found_filters": "[fr] No products match your current filters.",
    "suggestions_title": "[fr] Suggestions",
    "suggestion_see_all_products": "[fr] See all products in this category:",
    "all_category_products": "[fr] All Category Products",
    "suggestion_try_removing_filters": "[fr] Try removing some filters:",
    "remove_a_filter": "[fr] Remove a filter",
    "suggestion_return_home": "[fr] Return to the homepage:",
    "return_to_homepage": "[fr] Return to Homepage",
    "no_subcategories": "[fr] No subcategories available.",
    "popular_categories": "[fr] Popular Categories", "top_deals_in": "[fr] Top Deals in",
    "products_with_significant_price_drop": "[fr] Products with a significant price drop",
    "hottest_in": "[fr] Hottest in", "product_reviews_title": "[fr] Product Reviews",
    "helpful_reviews_subtitle": "[fr] Helpful reviews from our users",
    "popular_manufacturers": "[fr] Popular Manufacturers",
    "price_alert_button": "[fr] Set Price Alert",
    "price_alert_prompt_in": "[fr] Never miss a deal for products in",
    "return_to": "[fr] Return to",
    "info_for_certified_store": "[fr] Information for certified store",
    "showing_products_from_store": "[fr] Showing products from store",
    "remove_filter": "[fr] Remove this filter",
    "breadcrumbHome": "[fr] BestPrice",
    "breadcrumbAllProductsInCategory": "[fr] All products in the {{categoryName}} category",
    "breadcrumbAllProductsAndSubcategoriesInCategory": "[fr] All products and subcategories in the {{categoryName}} category",
    "loadingProduct": "[fr] Loading Product...",
    "addToShoppingList": "[fr] Add to Shopping List", "addToComparison": "[fr] Add to Comparison",
    "iWantIt": "[fr] I Want It", "iHaveIt": "[fr] I Have It",
    "notifyPriceDrop": "[fr] Notify for Price Drop", "addToCollection": "[fr] Add to Collection",
    "priceFrom": "[fr] From", "inStores": "[fr] in {{count}} stores",
    "storesCount": "[fr] Stores ({{count}})",
    "available": "[fr] Available", "nearMe": "[fr] Near Me",
    "deliveryWithService": "[fr] Delivery with {{serviceName}}",
    "coupons": "[fr] Coupons", "color": "[fr] Color",
    "officialResellers": "[fr] Official Resellers", "priceHistoryTitle": "[fr] Price History",
    "productDetails": "[fr] Product Details", "userReviews": "[fr] User Reviews ({{count}})",
    "questionsAndAnswers": "[fr] Questions & Answers ({{count}})",
    "similarProducts": "[fr] Similar Products", "dealsInCategory": "[fr] Deals in {{categoryName}}",
    "addToCart": "[fr] Add to Cart", "buyNow": "[fr] Buy Now",
    "specifications": "[fr] Specifications", "reviews": "[fr] Reviews",
    "relatedProducts": "[fr] Related Products", "writeReview": "[fr] Write a Review",
    "outOfStock": "[fr] Out of Stock",
    "availableAt": "[fr] Available at {{count}} stores", "noStoresAvailable": "[fr] Currently unavailable",
    "priceRange": "[fr] Price Range", "comparePrices": "[fr] Compare {{count}} Prices",
    "viewAllStores": "[fr] View all stores", "productDescription": "[fr] Description",
    "share": "[fr] Share", "removeFromFavorites": "[fr] Remove from Favorites",
    "priceHistory": "[fr] Price History",
    "certifiedStoresTooltip": "[fr] Show only products from certified stores",
    "vendorPopupCertification": "[fr] Certification: {{certificationType}}",
    "vendorPopupInformation": "[fr] Information",
    "vendorPopupAddressNotAvailable": "[fr] Online Only Store",
    "vendorPopupPaymentMethods": "[fr] PAYMENT METHODS",
    "vendorPopupLearnMore": "[fr] Learn More", "vendorPopupViewInStore": "[fr] View in Store",
    "openingHoursNotAvailable": "[fr] Opening hours information not available",
    "closedToday": "[fr] Closed today", "openUntil": "[fr] Open until {{time}}",
    "closedOpensAt": "[fr] Closed - Opens at {{time}}", "closedForToday": "[fr] Closed for today",
    "openingHoursError": "[fr] Error in opening hours",
    "loginRequired": "[fr] Login Required",
    "loginToAddToFavorites": "[fr] Please log in to add this product to your favorites",
    "productAddedToFavorites": "{{productName}} [fr] has been added to your favorites",
    "linkCopied": "[fr] Link Copied", "productLinkCopied": "[fr] Product link copied to clipboard",
    "copyFailed": "[fr] Copy Failed", "couldNotCopyLink": "[fr] Could not copy link",
    "loginToSetPriceAlert": "[fr] Please log in to set a price alert",
    "loadingVendor": "[fr] Loading store...", "allStores": "[fr] Stores",
    "certifiedStoreLinkText": "[fr] Certified Store ({{certificationLevel}})",
    "certifiedStoreFullText": "{{vendorName}} [fr] is a certified store ({{certificationLevel}})",
    "memberSinceDate": "[fr] On BestPrice since {{date}}",
    "ratingTooltip": "{{rating}} [fr] stars from {{count}} ratings",
    "social_facebook": "[fr] Facebook", "social_twitter": "[fr] Twitter", "social_instagram": "[fr] Instagram", "social_youtube": "[fr] YouTube", "social_linkedin": "[fr] LinkedIn", "social_tiktok": "[fr] TikTok",
    "additionalStores": "{{count}} [fr] more {{storeLabel}}",
    "storeLabelSingular": "[fr] store", "storeLabelPlural": "[fr] stores",
    "logoFor": "{{name}} [fr] logo", "screenshotFor": "{{name}} [fr] Screenshot",
    "authorizedReseller": "[fr] Authorized Reseller", "previewWebsite": "[fr] Preview Website",
    "dealsFromVendor": "[fr] Deals from {{vendorName}}",
    "popularCategoriesInVendor": "[fr] Popular Categories in {{vendorName}}",
    "viewAllVendorProducts": "[fr] View all products<span class=\"hide-mobile\"> of the store</span>",
    "storeReviewsTitle": "[fr] Store Reviews for {{vendorName}}",
    "reviewCount": "{{count}} [fr] reviews", "rateIt": "[fr] Rate It",
    "reviewsPlaceholder": "[fr] (Reviews display - Implementation needed)",
    "servicePointsTitle": "[fr] Service Points for {{vendorName}}",
    "servicePointsCount": "{{count}} [fr] points",
    "storeAndPickup": "[fr] Store / Pickup Point",
    "mapPlaceholderText": "[fr] Map Placeholder - Requires Map Library",
    "noLanguagesInRegion": "[fr] No languages listed for this region yet.",
    "toggleTheme": "[fr] Toggle theme",
    "productsYouWant": "[fr] Products you want", "productsYouHave": "[fr] Products you have",
    "myOffers": "[fr] My Offers", "priceDrops": "[fr] Price Drops",
    "myCollections": "[fr] My Collections", "newCollection": "[fr] New Collection...",
    "creditsClub": "[fr] Credits Club", "savedOrders": "[fr] Saved Orders",
    "myQuestions": "[fr] My Questions", "myReviews": "[fr] My Reviews",
    "myFriends": "[fr] My Friends", "viewProfileTooltip": "[fr] View your profile",
    "userMenuCaretAlt": "[fr] Open user menu",
    "backToTop": "[fr] Back to Top",
    "bestpriceSloganShort": "[fr] The truly best price",
    "bestpriceSloganLong": "[fr] BestPrice is the first and largest price comparison service in Greece.",
    "bestpriceSloganFindDeals": "[fr] At BestPrice you will quickly and easily find real offers and the best price from the largest stores.",
    "bestpriceGive": "[fr] BestPrice Give", "footerBestPriceSectionTitle": "[fr] BestPrice",
    "aboutUs": "[fr] About Us", "ourBlog": "[fr] Our Blog",
    "buyingGuides": "[fr] Buying Guides", "purchaseInsurance": "[fr] Purchase Insurance",
    "advertising": "[fr] Advertising", "bestpriceCertification": "[fr] BestPrice Certification",
    "customerReviewAwards": "[fr] Customer Review Awards", "ourAwards": "[fr] Our Awards",
    "ourTeam": "[fr] Our Team", "bestpriceAssistant": "[fr] BestPrice Assistant",
    "jobOpenings": "[fr] Job Openings ({{count}})", "contactUs": "[fr] Contact",
    "inNumbers": "[fr] In Numbers",
    "storeCountLink": "{{count}} [fr] stores", "productCountLink": "{{count}} [fr] products",
    "brandCountLink": "{{count}} [fr] manufacturers","dealCountLink": "{{count}} [fr] offers",
    "termsAndPrivacy": "[fr] Terms & Privacy", "termsOfUse": "[fr] Terms of Use",
    "privacyPolicy": "[fr] Privacy Policy", "cookiePolicy": "[fr] Cookie Policy",
    "gdprLink": "[fr] GDPR", "dsaLink": "[fr] DSA",
    "bestpriceForMerchants": "[fr] BestPrice For Merchants",
    "merchantsSectionSlogan1": "[fr] Do you have an online store?",
    "merchantsSectionSlogan2": "[fr] See how BestPrice can help you increase your sales!",
    "forMerchantsButton": "[fr] For Merchants",
    "bestpriceForBrands": "[fr] BestPrice For Brands",
    "brandsSectionSlogan": "[fr] BestPrice for Brands will offer useful information & services to manufacturers (Brands).",
    "moreInfoButton": "[fr] More Info",
    "bestpriceOnFacebook": "[fr] BestPrice on Facebook", "bestpriceOnX": "[fr] BestPrice on X",
    "bestpriceOnThreads": "[fr] BestPrice on Threads", "bestpriceOnInstagram": "[fr] BestPrice on Instagram",
    "bestpriceOnTikTok": "[fr] BestPrice on TikTok", "bestpriceOnYouTube": "[fr] BestPrice on YouTube",
    "bestpriceOnLinkedIn": "[fr] BestPrice on LinkedIn",
    "homepageTitle": "[fr] Homepage",
    "changeLanguage": "[fr] Change Language", "selectYourLanguageTitle": "[fr] Select Your Language",
    "suggestedLanguages": "[fr] Suggested Languages", "allLanguages": "[fr] All Languages",
    "languageCategoryEurope": "[fr] Europe", "languageCategoryAsia": "[fr] Asia",
    "languageCategoryAmericas": "[fr] Americas", "languageCategoryAfrica": "[fr] Africa & Middle East",
    "languageCategoryEasternEurope": "[fr] Eastern Europe", "languageCategoryWesternEurope": "[fr] Western Europe",
    "allBrands": "[fr] All Brands", "productsFromBrand": "[fr] Products from {{brandName}}",
    "searchResultsFor": "[fr] Search results for \"{{searchTerm}}\"",
    "noResultsFound": "[fr] No results found for \"{{searchTerm}}\"",
    "sortBy": "[fr] Sort by", "viewAsGrid": "[fr] Grid View",
    "viewAsList": "[fr] List View", "itemsPerPage": "[fr] Items per page",
    "page": "[fr] Page", "of": "[fr] of", "nextPage": "[fr] Next", "previousPage": "[fr] Previous",
    "todaysDeals": "[fr] Today's Deals", "filterBy": "[fr] Filter by",
    "shoppingCart": "[fr] Shopping Cart", "proceedToCheckout": "[fr] Proceed to Checkout",
    "item": "[fr] Item", "quantity": "[fr] Quantity", "subtotal": "[fr] Subtotal", "total": "[fr] Total",
    "emptyCart": "[fr] Your cart is empty.", "continueShopping": "[fr] Continue Shopping",
    "shippingAddress": "[fr] Shipping Address", "billingAddress": "[fr] Billing Address",
    "paymentInformation": "[fr] Payment Information", "placeOrder": "[fr] Place Order",
    "orderSummary": "[fr] Order Summary", "discountCode": "[fr] Discount Code", "apply": "[fr] Apply",
    "paymentMethod_credit_card": "[fr] Credit Card", "paymentMethod_bank_transfer": "[fr] Bank Transfer",
    "paymentMethod_paypal": "[fr] PayPal", "paymentMethod_cash_on_delivery": "[fr] Cash on Delivery",
    "paymentMethod_pickup_from_store": "[fr] Pickup from Store", "paymentMethod_klarna": "[fr] Klarna",
    "paymentMethod_apple_pay": "[fr] Apple Pay", "paymentMethod_google_pay": "[fr] Google Pay",
    "paymentMethod_ideal": "[fr] iDEAL", "paymentMethod_crypto": "[fr] Cryptocurrency",
    "paymentMethod_pay_by_link": "[fr] Pay by Link", "paymentMethod_pickup_via": "[fr] Pickup via Courier/Service",
    'technology': '[fr] Technology', 'home-garden': '[fr] Home & Garden', 'fashion': '[fr] Fashion',
    /* ... and so on for all category slugs for FR ... */
    'hi-fi-systems': '[fr] Hi-Fi Systems', // Ensure all keys are present
  },
  // ============================ German (de) - Placeholder, needs full translation =============================
  de: {
    email: '[de] Email', password: '[de] Password', /* ... and so on for ALL keys for DE ... */
    languageCategoryEasternEurope: "[de] Eastern Europe", 
    languageCategoryWesternEurope: "[de] Western Europe",
    'technology': '[de] Technology', /* ... and all category slugs for DE ... */
    'hi-fi-systems': '[de] Hi-Fi Systems', // Ensure all keys are present
  }
};


// ================================================================================================
// CONTEXT CREATION
// ================================================================================================

const LanguageContext = createContext<LanguageContextType>({
  language: 'el', // Default language
  setLanguage: (lang: Language) => {
    console.warn(
      `Attempted to call setLanguage with '${lang}' outside of a LanguageProvider. This is a no-op.`
    );
  },
  translations: defaultTranslations, // Provide the full default translations
  isLoaded: false,
});


// ================================================================================================
// LANGUAGE PROVIDER COMPONENT
// ================================================================================================

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('el');
  // Initialize translations state with defaultTranslations.
  const [translations, setTranslationsState] = useState<Translations>(defaultTranslations);
  const [isLoaded, setIsLoaded] = useState(false);
  const { user } = useAuth();

  // --- Effect for detecting and setting the initial language ---
  useEffect(() => {
    const detectLanguage = async () => {
      let detectedLang: Language = 'el'; // Default application language
      const browserLang = navigator.language.split('-')[0];
      const validLangs: Language[] = ['en', 'el', 'es', 'fr', 'de'];

      // Check browser language
      if (validLangs.includes(browserLang as Language)) {
        detectedLang = browserLang as Language;
      }

      // Check user preference from database if user is logged in
      if (user) {
        try {
          const { data, error } = await supabase
            .from('profiles')
            .select('language')
            .eq('id', user.id)
            .single();

          if (data?.language && !error && validLangs.includes(data.language as Language)) {
            detectedLang = data.language as Language;
          } else if (error) {
            console.error('Error fetching user language preference from DB:', error);
          }
        } catch (fetchError) {
          console.error('Exception fetching user language preference:', fetchError);
        }
      }

      // Check localStorage (this can override browser/DB preference)
      const savedLang = localStorage.getItem('language');
      if (savedLang && validLangs.includes(savedLang as Language)) {
        detectedLang = savedLang as Language;
      }

      setLanguageState(detectedLang);
      setIsLoaded(true); // Mark as loaded *after* all language detection logic
    };

    detectLanguage();
  }, [user]); // Re-run this effect if the user object changes (e.g., login/logout)


  // --- Effect for loading custom translations from the database ---
  useEffect(() => {
    if (!isLoaded) {
      // Only attempt to load custom translations if initial language setup is complete
      // and default translations are already set by useState.
      return;
    }

    const loadCustomTranslations = async () => {
      // Start with a deep copy of defaultTranslations.
      // This ensures all languages and keys from the default set are present.
      const newMergedTranslations = JSON.parse(JSON.stringify(defaultTranslations)) as Translations;

      try {
        const { data, error } = await (supabase as any).from('translations').select('*');

        if (error) {
          console.error('Error fetching custom translations:', error.message || error);
          // Fallback: use the default translations (which newMergedTranslations currently is)
          setTranslationsState(newMergedTranslations);
          return;
        }

        if (data && data.length > 0) {
          data.forEach((item: any) => {
            if (item && item.key) {
              (Object.keys(newMergedTranslations) as Language[]).forEach(lang => {
                if (newMergedTranslations[lang] && item[lang] && typeof item[lang] === 'string') {
                  newMergedTranslations[lang][item.key] = item[lang];
                }
              });
            }
          });
        }
        setTranslationsState(newMergedTranslations);
      } catch (processingError) {
        console.error('Error processing custom translations:', processingError);
        // Fallback: use the default translations
        setTranslationsState(newMergedTranslations);
      }
    };

    loadCustomTranslations();
  }, [isLoaded]); // Dependency: `isLoaded`. `defaultTranslations` and `supabase` are stable.


  // --- Memoized callback for setting the language ---
  const setLanguageCallback = useCallback((lang: Language) => {
    const validLangs: Language[] = ['en', 'el', 'es', 'fr', 'de'];
    if (!validLangs.includes(lang)) {
      console.warn(`Attempted to set an invalid language: ${lang}`);
      return;
    }

    localStorage.setItem('language', lang);
    setLanguageState(lang);

    if (user) {
      supabase
        .from('profiles')
        .update({ language: lang } as any) // Cast if schema types are strict
        .eq('id', user.id)
        .then(({ error: updateError }) => {
          if (updateError) {
            console.error('Error saving language preference to DB:', updateError);
          }
        });
    }
  }, [user]); // `supabase` client is generally stable.

  // --- Provide the context value ---
  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage: setLanguageCallback,
        translations,
        isLoaded
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};


// ================================================================================================
// HOOK TO CONSUME CONTEXT
// ================================================================================================

export const useLanguageContext = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    // This error is thrown by React itself if useContext is used outside a provider.
    // This custom message provides more specific guidance.
    throw new Error('useLanguageContext must be used within a LanguageProvider');
  }
  // Additionally, you could check if it's the default context value,
  // which also indicates a missing Provider, though React's error #310 usually catches this.
  // Example: if (context.setLanguage === LanguageContext.Consumer._context._currentValue.setLanguage) { ... }
  return context;
};
