import { createContext, useContext, useEffect, useState, ReactNode } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';

type Language = 'en' | 'el' | 'es' | 'fr' | 'de';
type Translations = Record<string, Record<string, string>>;

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  translations: Translations;
  isLoaded: boolean;
}

// This defaultTranslations should be the one you confirmed was complete
// and working with the AI-generated modal. I'll use the last comprehensive one.
const defaultTranslations: Translations = {
  en: {
    // Auth
    email: 'Email', password: 'Password', forgotPassword: 'Forgot Password?', register: 'Register',
    signIn: 'Sign In', loggingIn: 'Logging in...', emailPlaceholder: 'email@example.com', orContinueWith: 'Or continue with',
    google: 'Google', facebook: 'Facebook', twitter: 'Twitter', createAccount: 'Create Account',
    dontHaveAccount: "Don't have an account?", alreadyHaveAccount: 'Already have an account?', fullName: 'Full Name', confirmPassword: 'Confirm Password',
    agreeToTerms: 'I agree to the Terms of Service and Privacy Policy',
    creatingAccount: 'Creating Account...', resetYourPassword: 'Reset Your Password',
    enterEmailForReset: 'Enter your email address and we will send you a link to reset your password.',
    sendResetLink: 'Send Reset Link', sendingResetLink: 'Sending...',
    resetPasswordEmailSent: 'Password reset email sent. Please check your inbox.',
    backToLogin: 'Back to Login', createNewPassword: 'Create New Password',
    newPassword: 'New Password', updatePassword: 'Update Password',
    updating: 'Updating...', passwordUpdated: 'Password Updated',
    passwordSuccessfullyChanged: 'Your password has been successfully changed.',
    passwordResetFailed: 'Password Reset Failed',
    errorProcessingRequest: 'There was an error processing your request.',
    passwordTooShort: 'Password Too Short', passwordMinLength: 'Password must be at least 6 characters.',
    passwordsDontMatch: 'Passwords Don\'t Match', pleaseCheckPasswords: 'Please check that both passwords match.',
    languageSettings: 'Language Settings', selectLanguage: 'Select Language', english: 'English', greek: 'Greek',
    spanish: 'Spanish', french: 'French', german: 'German', systemLanguage: 'System Language (Default)',
    save: 'Save', cancel: 'Cancel', loading: 'Loading...', success: 'Success',
    error: 'Error', wallet: 'Wallet', myWallet: 'My Wallet', manageWallet: 'Manage your funds, transactions, and ad payments',
    deposit: 'Deposit', transactions: 'Transactions', connectWallet: 'Connect Wallet', addFunds: 'Add Funds',
    amount: 'Amount ($)', enterAmount: 'Enter amount', paymentMethod: 'Payment Method', processing: 'Processing...',
    myAccount: 'My Account', profile: 'Profile', favorites: 'Favorites', recentlyViewed: 'Recently Viewed',
    priceAlerts: 'Price Alerts', settings: 'Settings', logout: 'Logout', myProfile: 'My Profile',
    managePersonalInfo: 'Manage your personal information',
    name: 'Name', memberSince: 'Member since', role: 'Role', administrator: 'Administrator',
    regularUser: 'Regular User', editProfile: 'Edit Profile', accountSummary: 'Account Summary', categories: 'Categories',
    gifts: 'Gifts', deals: 'Deals', clearFilters: 'Clear filters', finalPrice: 'Final price',
    yes: "Yes", no: "No", ok: "OK", close: "Close",
    showMore: "Show More", showLess: "Show Less", all: "All", selectOption: "Select an option",
    optional: "Optional", required: "Required", back: "Back", next: "Next",
    submit: "Submit", search: "Search", searchPlaceholder: "Search for products...",
    notFoundPageTitle: "Page Not Found", notFoundMessage: "Oops! The page you are looking for does not exist.",
    recently_viewed_title: "Recently Viewed",
    "product_singular": "product", "product_plural": "{{count}} products",
    "rating_label": "Rating", "reviews_label_singular": "review", "reviews_label_plural": "{{count}} reviews",
    "from_vendor": "from", "with": "with",
    "no_products_in_category": "There are no products in this category yet.",
    "filters_title": "Filters", "remove_all_filters_tooltip": "Remove all filters",
    "show_only_title": "Show only", "deals_label": "Deals",
    "deals_title": "Products with significant price drop",
    "certified_label": "Certified", "certified_stores_title": "Certified Stores",
    "instock_label": "In Stock", "instock_title": "Only products available in stock",
    "boxnow_delivery_title": "BOX NOW Delivery",
    "boxnow_tooltip": "Pick up your order from a BOX NOW locker 24/7",
    "delivery_label": "BOX NOW", "manufacturer_title": "Manufacturer",
    "show_less_manufacturers": "Show less manufacturers", "show_all_manufacturers": "Show all manufacturers",
    "show_all": "Show All",
    "show_less_options": "Show less options for", "show_all_options": "Show all options for",
    "remove_instock_filter": "Remove 'In Stock' filter", "remove_deals_filter": "Remove 'Deals' filter",
    "remove_certified_filter": "Remove 'Certified' filter", "remove_nearby_filter": "Remove 'Nearby' filter",
    "remove_boxnow_filter": "Remove 'BOX NOW' filter",
    "remove_brand_filter": "Remove brand filter", "remove_spec_filter": "Remove spec filter",
    "reset_all_filters": "Reset all filters", "clear_all_filters": "Clear All",
    "selected_deals": "Selected Deals", "popular_choices": "Popular Choices",
    "sort_most_popular": "Most Popular", "sort_newest": "Newest",
    "sort_cheapest": "Cheapest", "sort_most_expensive": "Most Expensive",
    "sort_alphabetical": "Alphabetical (A-Z)", "sort_most_reviews": "Most Reviews",
    "sort_by_manufacturer": "By Manufacturer", "sort_num_stores": "Number of Stores",
    "price_alert_for": "Price Alert for",
    "no_products_found_filters": "No products match your current filters.",
    "suggestions_title": "Suggestions",
    "suggestion_see_all_products": "See all products in this category:",
    "all_category_products": "All Category Products",
    "suggestion_try_removing_filters": "Try removing some filters:",
    "remove_a_filter": "Remove a filter",
    "suggestion_return_home": "Return to the homepage:",
    "return_to_homepage": "Return to Homepage",
    "no_subcategories": "No subcategories available.",
    "popular_categories": "Popular Categories", "top_deals_in": "Top Deals in",
    "products_with_significant_price_drop": "Products with a significant price drop",
    "hottest_in": "Hottest in", "product_reviews_title": "Product Reviews",
    "helpful_reviews_subtitle": "Helpful reviews from our users",
    "popular_manufacturers": "Popular Manufacturers",
    "price_alert_button": "Set Price Alert",
    "price_alert_prompt_in": "Never miss a deal for products in",
    "return_to": "Return to",
    "info_for_certified_store": "Information for certified store",
    "showing_products_from_store": "Showing products from store",
    "remove_filter": "Remove this filter",
    "breadcrumbHome": "BestPrice",
    "breadcrumbAllProductsInCategory": "All products in the {{categoryName}} category",
    "breadcrumbAllProductsAndSubcategoriesInCategory": "All products and subcategories in the {{categoryName}} category",
    "loadingProduct": "Loading Product...",
    "addToShoppingList": "Add to Shopping List", "addToComparison": "Add to Comparison",
    "iWantIt": "I Want It", "iHaveIt": "I Have It",
    "notifyPriceDrop": "Notify for Price Drop", "addToCollection": "Add to Collection",
    "priceFrom": "From", "inStores": "in {{count}} stores",
    "storesCount": "Stores ({{count}})",
    "available": "Available", "nearMe": "Near Me",
    "deliveryWithService": "Delivery with {{serviceName}}",
    "coupons": "Coupons", "color": "Color",
    "officialResellers": "Official Resellers", "priceHistoryTitle": "Price History",
    "productDetails": "Product Details", "userReviews": "User Reviews ({{count}})",
    "questionsAndAnswers": "Questions & Answers ({{count}})",
    "similarProducts": "Similar Products", "dealsInCategory": "Deals in {{categoryName}}",
    "addToCart": "Add to Cart", "buyNow": "Buy Now",
    "specifications": "Specifications", "reviews": "Reviews",
    "relatedProducts": "Related Products", "writeReview": "Write a Review",
    "outOfStock": "Out of Stock",
    "availableAt": "Available at {{count}} stores", "noStoresAvailable": "Currently unavailable",
    "priceRange": "Price Range", "comparePrices": "Compare {{count}} Prices",
    "viewAllStores": "View all stores", "productDescription": "Description",
    "share": "Share", "removeFromFavorites": "Remove from Favorites",
    "priceHistory": "Price History",
    "certifiedStoresTooltip": "Show only products from certified stores",
    "vendorPopupCertification": "Certification: {{certificationType}}",
    "vendorPopupInformation": "Information",
    "vendorPopupAddressNotAvailable": "Online Only Store",
    "vendorPopupPaymentMethods": "PAYMENT METHODS",
    "vendorPopupLearnMore": "Learn More", "vendorPopupViewInStore": "View in Store",
    "openingHoursNotAvailable": "Opening hours information not available",
    "closedToday": "Closed today", "openUntil": "Open until {{time}}",
    "closedOpensAt": "Closed - Opens at {{time}}", "closedForToday": "Closed for today",
    "openingHoursError": "Error in opening hours",
    "loginRequired": "Login Required",
    "loginToAddToFavorites": "Please log in to add this product to your favorites",
    "productAddedToFavorites": "{{productName}} has been added to your favorites",
    "linkCopied": "Link Copied", "productLinkCopied": "Product link copied to clipboard",
    "copyFailed": "Copy Failed", "couldNotCopyLink": "Could not copy link",
    "loginToSetPriceAlert": "Please log in to set a price alert",
    "loadingVendor": "Loading store...", "allStores": "Stores",
    "certifiedStoreLinkText": "Certified Store ({{certificationLevel}})",
    "certifiedStoreFullText": "{{vendorName}} is a certified store ({{certificationLevel}})",
    "memberSinceDate": "On BestPrice since {{date}}",
    "ratingTooltip": "{{rating}} stars from {{count}} ratings",
    "social_facebook": "Facebook", "social_twitter": "Twitter", "social_instagram": "Instagram", "social_youtube": "YouTube", "social_linkedin": "LinkedIn", "social_tiktok": "TikTok",
    "additionalStores": "{{count}} more {{storeLabel}}",
    "storeLabelSingular": "store", "storeLabelPlural": "stores",
    "logoFor": "{{name}} logo", "screenshotFor": "{{name}} Screenshot",
    "authorizedReseller": "Authorized Reseller", "previewWebsite": "Preview Website",
    "dealsFromVendor": "Deals from {{vendorName}}",
    "popularCategoriesInVendor": "Popular Categories in {{vendorName}}",
    "viewAllVendorProducts": "View all products<span class=\"hide-mobile\"> of the store</span>",
    "storeReviewsTitle": "Store Reviews for {{vendorName}}",
    "reviewCount": "{{count}} reviews", "rateIt": "Rate It",
    "reviewsPlaceholder": "(Reviews display - Implementation needed)",
    "servicePointsTitle": "Service Points for {{vendorName}}",
    "servicePointsCount": "{{count}} points",
    "storeAndPickup": "Store / Pickup Point",
    "mapPlaceholderText": "Map Placeholder - Requires Map Library",
    "noLanguagesInRegion": "No languages listed for this region yet.",
    "toggleTheme": "Toggle theme",
    "productsYouWant": "Products you want", "productsYouHave": "Products you have",
    "myOffers": "My Offers", "priceDrops": "Price Drops",
    "myCollections": "My Collections", "newCollection": "New Collection...",
    "creditsClub": "Credits Club", "savedOrders": "Saved Orders",
    "myQuestions": "My Questions", "myReviews": "My Reviews",
    "myFriends": "My Friends", "viewProfileTooltip": "View your profile",
    "userMenuCaretAlt": "Open user menu",
    "backToTop": "Back to Top",
    "bestpriceSloganShort": "The truly best price",
    "bestpriceSloganLong": "BestPrice is the first and largest price comparison service in Greece.",
    "bestpriceSloganFindDeals": "At BestPrice you will quickly and easily find real offers and the best price from the largest stores.",
    "bestpriceGive": "BestPrice Give", "footerBestPriceSectionTitle": "BestPrice",
    "aboutUs": "About Us", "ourBlog": "Our Blog",
    "buyingGuides": "Buying Guides", "purchaseInsurance": "Purchase Insurance",
    "advertising": "Advertising", "bestpriceCertification": "BestPrice Certification",
    "customerReviewAwards": "Customer Review Awards", "ourAwards": "Our Awards",
    "ourTeam": "Our Team", "bestpriceAssistant": "BestPrice Assistant",
    "jobOpenings": "Job Openings ({{count}})", "contactUs": "Contact",
    "inNumbers": "In Numbers",
    "storeCountLink": "{{count}} stores", "productCountLink": "{{count}} products",
    "brandCountLink": "{{count}} manufacturers","dealCountLink": "{{count}} offers",
    "termsAndPrivacy": "Terms & Privacy", "termsOfUse": "Terms of Use",
    "privacyPolicy": "Privacy Policy", "cookiePolicy": "Cookie Policy",
    "gdprLink": "GDPR", "dsaLink": "DSA",
    "bestpriceForMerchants": "BestPrice For Merchants",
    "merchantsSectionSlogan1": "Do you have an online store?",
    "merchantsSectionSlogan2": "See how BestPrice can help you increase your sales!",
    "forMerchantsButton": "For Merchants",
    "bestpriceForBrands": "BestPrice For Brands",
    "brandsSectionSlogan": "BestPrice for Brands will offer useful information & services to manufacturers (Brands).",
    "moreInfoButton": "More Info",
    "bestpriceOnFacebook": "BestPrice on Facebook", "bestpriceOnX": "BestPrice on X",
    "bestpriceOnThreads": "BestPrice on Threads", "bestpriceOnInstagram": "BestPrice on Instagram",
    "bestpriceOnTikTok": "BestPrice on TikTok", "bestpriceOnYouTube": "BestPrice on YouTube",
    "bestpriceOnLinkedIn": "BestPrice on LinkedIn",
    "homepageTitle": "Homepage",
    "changeLanguage": "Change Language", "selectYourLanguageTitle": "Select Your Language",
    "suggestedLanguages": "Suggested Languages", "allLanguages": "All Languages",
    "languageCategoryEurope": "Europe", "languageCategoryAsia": "Asia",
    "languageCategoryAmericas": "Americas", "languageCategoryAfrica": "Africa & Middle East",
    "languageCategoryEasternEurope": "Eastern Europe", "languageCategoryWesternEurope": "Western Europe",
    "allBrands": "All Brands", "productsFromBrand": "Products from {{brandName}}",
    "searchResultsFor": "Search results for \"{{searchTerm}}\"",
    "noResultsFound": "No results found for \"{{searchTerm}}\"",
    "sortBy": "Sort by", "viewAsGrid": "Grid View",
    "viewAsList": "List View", "itemsPerPage": "Items per page",
    "page": "Page", "of": "of", "nextPage": "Next", "previousPage": "Previous",
    "todaysDeals": "Today's Deals", "filterBy": "Filter by",
    "shoppingCart": "Shopping Cart", "proceedToCheckout": "Proceed to Checkout",
    "item": "Item", "quantity": "Quantity", "subtotal": "Subtotal", "total": "Total",
    "emptyCart": "Your cart is empty.", "continueShopping": "Continue Shopping",
    "shippingAddress": "Shipping Address", "billingAddress": "Billing Address",
    "paymentInformation": "Payment Information", "placeOrder": "Place Order",
    "orderSummary": "Order Summary", "discountCode": "Discount Code", "apply": "Apply",
    "paymentMethod_credit_card": "Credit Card", "paymentMethod_bank_transfer": "Bank Transfer",
    "paymentMethod_paypal": "PayPal", "paymentMethod_cash_on_delivery": "Cash on Delivery",
    "paymentMethod_pickup_from_store": "Pickup from Store", "paymentMethod_klarna": "Klarna",
    "paymentMethod_apple_pay": "Apple Pay", "paymentMethod_google_pay": "Google Pay",
    "paymentMethod_ideal": "iDEAL", "paymentMethod_crypto": "Cryptocurrency",
    "paymentMethod_pay_by_link": "Pay by Link", "paymentMethod_pickup_via": "Pickup via Courier/Service",
    'technology': 'Technology', 'home-garden': 'Home & Garden', 'fashion': 'Fashion',
    'health-beauty': 'Health & Beauty', 'kids-baby': 'Kids & Baby', 'hobby-sports': 'Hobby & Sports',
    'auto-moto': 'Auto & Moto',
    'mobile-telephony': 'Mobile Telephony', 'computers': 'Computers', 'laptops-accessories': 'Laptops & Accessories',
    'visual': 'Visual', 'smartwatches-wearables': 'Smartwatches & Wearables', 'tablets-accessories': 'Tablets & Accessories',
    'video-games': 'Video Games', 'audio': 'Audio', 'photo-video': 'Photo & Video',
    'electronics': 'Electronics', 'telephony': 'Telephony', 'gadgets': 'Gadgets',
    'home-appliances': 'Home Appliances', 'tools': 'Tools', 'furniture': 'Furniture',
    'garden': 'Garden', 'home-items': 'Home Items', 'linens': 'Linens',
    'lighting': 'Lighting', 'kitchenware': 'Kitchenware', 'food-beverages': 'Food & Beverages',
    'electrical-supplies': 'Electrical Supplies', 'smoking-accessories': 'Smoking Accessories', 'office-supplies': 'Office Supplies',
    'gift-items': 'Gift Items', 'security-systems': 'Security Systems', 'professional-equipment': 'Professional Equipment',
    'seasonal-items': 'Seasonal Items', 'shopping-bags': 'Shopping Bags', 'shopping-trolleys': 'Shopping Trolleys',
    'church-items': 'Church Items', 'pet-supplies': 'Pet Supplies', 'womens-fashion': "Women's Fashion",
    'mens-fashion': "Men's Fashion", 'watches': 'Watches', 'jewelry': 'Jewelry',
    'eyewear': 'Eyewear', 'converse-all-star': 'Converse All Star', 'rain-umbrellas': 'Rain Umbrellas',
    'shoe-accessories': 'Shoe Accessories', 'kids-baby-fashion': "Kids & Baby Fashion", 'sneakers': 'Sneakers',
    'grooming': 'Grooming', 'pharmacy-products': 'Pharmacy Products', 'perfumes': 'Perfumes',
    'dietary-supplements': 'Dietary Supplements','grooming-devices': 'Grooming Devices', 'makeup': 'Makeup',
    'sunscreen-tanning': 'Sunscreen & Tanning', 'medical-supplies': 'Medical Supplies', 'manicure-pedicure': 'Manicure & Pedicure',
    'oral-hygiene': 'Oral Hygiene', 'sex-toys': 'Sex Toys', 'firming-slimming': 'Firming & Slimming',
    'cannabis-products': 'Cannabis Products', 'orthopedics': 'Orthopedics', 'patient-aids': 'Patient Aids',
    'optics': 'Optics', 'korean-cosmetics': 'Korean Cosmetics', 'kids-toys': "Kids' Toys",
    'school-supplies': 'School Supplies', 'baby-toys': 'Baby Toys', 'baby-items': 'Baby Items',
    'kids-linens': "Kids' Linens", 'christening-items': 'Christening Items', 'kids-watches': "Kids' Watches",
    'sports': 'Sports', 'cycling': 'Cycling', 'leisure-time': 'Leisure Time',
    'fishing-diving': 'Fishing & Diving', 'beach-sea-items': 'Beach & Sea Items', 'camping': 'Camping',
    'travel-items-bags': 'Travel Items & Bags', 'books': 'Books', 'hunting': 'Hunting',
    'fitness-equipment': 'Fitness Equipment', 'pet-supplies-hobby': 'Pet Supplies (Hobby)', 'drones-accessories': 'Drones & Accessories',
    'electric-scooters': 'Electric Scooters', 'hoverboards': 'Hoverboards', 'musical-instruments': 'Musical Instruments',
    'sports-accessories': 'Sports Accessories', 'exploration-items': 'Exploration Items',
    'womens-sportswear': "Women's Sportswear", 'womens-sports-shoes': "Women's Sports Shoes",
    'mens-sportswear': "Men's Sportswear", 'mens-sports-shoes': "Men's Sports Shoes",
    'car': 'Car', 'motorcycle': 'Motorcycle', 'boat': 'Boat',
    'truck-items': 'Truck Items', 'smartphones': 'Smartphones', 'iphone': 'iPhone',
    'mobile-cases': 'Mobile Cases', 'bluetooth-handsfree': 'Bluetooth Handsfree', 'handsfree': 'Handsfree',
    'mobile-chargers': 'Mobile Chargers', 'tempered-glass': 'Tempered Glass', 'screen-protectors': 'Screen Protectors',
    'power-banks': 'Power Banks', 'mobile-batteries': 'Mobile Batteries', 'selfie-sticks': 'Selfie Sticks',
    'mobile-holders': 'Mobile Holders', 'charging-data-cables': 'Charging & Data Cables', 'anti-lost-trackers': 'Anti-Lost Trackers',
    'mobile-spare-parts': 'Mobile Spare Parts', 'mobile-gimbals': 'Mobile Gimbals', 'stylus-pens': 'Stylus Pens',
    'stylus-accessories': 'Stylus Accessories', 'bluetooth-headset-accessories': 'Bluetooth Headset Accessories',
    'anti-lost-tracker-accessories': 'Anti-Lost Tracker Accessories',
    'pop-sockets': 'Pop Sockets', 'mobile-tripods': 'Mobile Tripods', 'mobile-service-tools': 'Mobile Service Tools',
    'mobile-charms': 'Mobile Charms', 'mobile-accessories': 'Mobile Accessories',
    'mobile-camera-protection': 'Mobile Camera Protection', 'mobile-camera-lenses': 'Mobile Camera Lenses',
    'mobile-signal-boosters': 'Mobile Signal Boosters', 'mobile-gaming-buttons': 'Mobile Gaming Buttons',
    'connection-packs': 'Connection Packs', 'portable-bluetooth-speakers-mobile': 'Portable Bluetooth Speakers (Mobile)',
    'ps5-games': 'PS5 Games', 'pc-games': 'PC Games', 'amplifiers-preamplifiers': 'Amplifiers & Preamplifiers',
    'hi-fi-systems': 'Hi-Fi Systems',
  },
  el: { /* ... Greek translations ... */ },
  es: { /* ... Spanish placeholder translations from 'en' ... */ },
  fr: { /* ... French placeholder translations from 'en' ... */ },
  de: { /* ... German placeholder translations from 'en' ... */ },
};

// Initialize 'el' structure by copying from 'en' and then overwriting with Greek specifics
defaultTranslations.el = JSON.parse(JSON.stringify(defaultTranslations.en));
const elTranslations = {
    email: 'Email', password: 'Κωδικός', forgotPassword: 'Ξεχάσατε τον κωδικό;', register: 'Εγγραφή',
    signIn: 'Σύνδεση', loggingIn: 'Γίνεται σύνδεση...', emailPlaceholder: 'email@example.com', orContinueWith: 'Ή συνεχίστε με',
    google: 'Google', facebook: 'Facebook', twitter: 'Twitter', createAccount: 'Δημιουργία Λογαριασμού',
    dontHaveAccount: 'Δεν έχετε λογαριασμό;', alreadyHaveAccount: 'Έχετε ήδη λογαριασμό;', fullName: 'Ονοματεπώνυμο', confirmPassword: 'Επαλήθευση Κωδικού',
    agreeToTerms: 'Συμφωνώ με τους Όρους Χρήσης και την Πολιτική Απορρήτου',
    creatingAccount: 'Δημιουργία Λογαριασμού...', resetYourPassword: 'Επαναφορά Κωδικού',
    enterEmailForReset: 'Εισαγάγετε το email σας και θα σας στείλουμε έναν σύνδεσμο για επαναφορά του κωδικού σας.',
    sendResetLink: 'Αποστολή Συνδέσμου', sendingResetLink: 'Αποστολή...',
    resetPasswordEmailSent: 'Το email επαναφοράς κωδικού στάλθηκε. Ελέγξτε τα εισερχόμενά σας.',
    backToLogin: 'Επιστροφή στη Σύνδεση', createNewPassword: 'Δημιουργία Νέου Κωδικού',
    newPassword: 'Νέος Κωδικός', updatePassword: 'Ενημέρωση Κωδικού',
    updating: 'Ενημέρωση...', passwordUpdated: 'Ο Κωδικός Ενημερώθηκε',
    passwordSuccessfullyChanged: 'Ο κωδικός σας άλλαξε επιτυχώς.',
    passwordResetFailed: 'Η Επαναφορά Κωδικού Απέτυχε',
    errorProcessingRequest: 'Παρουσιάστηκε σφάλμα κατά την επεξεργασία του αιτήματός σας.',
    passwordTooShort: 'Πολύ Κοντός Κωδικός', passwordMinLength: 'Ο κωδικός πρέπει να είναι τουλάχιστον 6 χαρακτήρες.',
    passwordsDontMatch: 'Οι Κωδικοί δεν Ταιριάζουν', pleaseCheckPasswords: 'Ελέγξτε ότι οι δύο κωδικοί ταιριάζουν.',
    languageSettings: 'Ρυθμίσεις Γλώσσας', selectLanguage: 'Επιλογή Γλώσσας', english: 'Αγγλικά', greek: 'Ελληνικά',
    spanish: 'Ισπανικά', french: 'Γαλλικά', german: 'Γερμανικά', systemLanguage: 'Γλώσσα Συστήματος (Προεπιλογή)',
    save: 'Αποθήκευση', cancel: 'Άκυρο', loading: 'Φόρτωση...', success: 'Επιτυχία',
    error: 'Σφάλμα', wallet: 'Πορτοφόλι', myWallet: 'Το Πορτοφόλι μου', manageWallet: 'Διαχείριση κεφαλαίων, συναλλαγών και διαφημίσεων',
    deposit: 'Κατάθεση', transactions: 'Συναλλαγές', connectWallet: 'Σύνδεση Πορτοφολιού', addFunds: 'Προσθήκη Χρημάτων',
    amount: 'Ποσό (€)', enterAmount: 'Εισάγετε ποσό', paymentMethod: 'Μέθοδος Πληρωμής', processing: 'Επεξεργασία...',
    myAccount: 'Ο Λογαριασμός μου', profile: 'Προφίλ', favorites: 'Αγαπημένα', recentlyViewed: 'Είδατε Πρόσφατα',
    priceAlerts: 'Ειδοποιήσεις Τιμών', settings: 'Ρυθμίσεις', logout: 'Αποσύνδεση', myProfile: 'Το Προφίλ μου',
    managePersonalInfo: 'Διαχείριση προσωπικών πληροφοριών',
    name: 'Όνομα', memberSince: 'Μέλος από', role: 'Ρόλος', administrator: 'Διαχειριστής',
    regularUser: 'Απλός Χρήστης', editProfile: 'Επεξεργασία Προφίλ', accountSummary: 'Σύνοψη Λογαριασμού', categories: 'Κατηγορίες',
    gifts: 'Δώρα', deals: 'Προσφορές', clearFilters: 'Καθαρισμός φίλτρων', finalPrice: 'Τελική τιμή',
    yes: "Ναι", no: "Όχι", ok: "OK", close: "Κλείσιμο",
    showMore: "Περισσότερα", showLess: "Λιγότερα", all: "Όλα", selectOption: "Επιλέξτε",
    optional: "Προαιρετικό", required: "Απαιτείται", back: "Πίσω", next: "Επόμενο",
    submit: "Υποβολή", search: "Αναζήτηση", searchPlaceholder: "Αναζήτηση προϊόντων...",
    notFoundPageTitle: "Η Σελίδα δεν Βρέθηκε", notFoundMessage: "Ουπς! Η σελίδα που αναζητάτε δεν υπάρχει.",
    recently_viewed_title: "Είδατε Πρόσφατα",
    "product_singular": "προϊόν", "product_plural": "{{count}} προϊόντα",
    "rating_label": "Βαθμολογία", "reviews_label_singular": "αξιολόγηση", "reviews_label_plural": "{{count}} αξιολογήσεις",
    "from_vendor": "από", "with": "με",
    "no_products_in_category": "Δεν υπάρχουν προϊόντα σε αυτή την κατηγορία ακόμα.",
    "filters_title": "Φίλτρα", "remove_all_filters_tooltip": "Αφαίρεση όλων των φίλτρων",
    "show_only_title": "Εμφάνιση μόνο", "deals_label": "Προσφορές",
    "deals_title": "Προϊόντα με σημαντική πτώση τιμής",
    "certified_label": "Πιστοποιημένα", "certified_stores_title": "Πιστοποιημένα Καταστήματα",
    "instock_label": "Διαθέσιμα", "instock_title": "Μόνο προϊόντα διαθέσιμα σε απόθεμα",
    "boxnow_delivery_title": "BOX NOW Παράδοση",
    "boxnow_tooltip": "Παραλάβετε την παραγγελία σας από ένα BOX NOW locker 24/7",
    "delivery_label": "BOX NOW", "manufacturer_title": "Κατασκευαστής",
    "show_less_manufacturers": "Λιγότεροι κατασκευαστές", "show_all_manufacturers": "Όλοι οι κατασκευαστές",
    "show_all": "Όλα",
    "show_less_options": "Λιγότερες επιλογές για", "show_all_options": "Όλες οι επιλογές για",
    "remove_instock_filter": "Αφαίρεση φίλτρου 'Διαθέσιμα'", "remove_deals_filter": "Αφαίρεση φίλτρου 'Προσφορές'",
    "remove_certified_filter": "Αφαίρεση φίλτρου 'Πιστοποιημένα'", "remove_nearby_filter": "Αφαίρεση φίλτρου 'Κοντινά'",
    "remove_boxnow_filter": "Αφαίρεση φίλτρου 'BOX NOW'",
    "remove_brand_filter": "Αφαίρεση φίλτρου κατασκευαστή", "remove_spec_filter": "Αφαίρεση φίλτρου χαρακτηριστικού",
    "reset_all_filters": "Επαναφορά όλων των φίλτρων", "clear_all_filters": "Καθαρισμός Όλων",
    "selected_deals": "Επιλεγμένες Προσφορές", "popular_choices": "Δημοφιλείς Επιλογές",
    "sort_most_popular": "Δημοφιλέστερα", "sort_newest": "Νεότερα",
    "sort_cheapest": "Φθηνότερα", "sort_most_expensive": "Ακριβότερα",
    "sort_alphabetical": "Αλφαβητικά (Α-Ω)", "sort_most_reviews": "Περισσότερες Αξιολογήσεις",
    "sort_by_manufacturer": " ανά Κατασκευαστή", "sort_num_stores": "Πλήθος Καταστημάτων",
    "price_alert_for": "Ειδοποίηση Τιμής για",
    "no_products_found_filters": "Κανένα προϊόν δεν αντιστοιχεί στα τρέχοντα φίλτρα σας.",
    "suggestions_title": "Προτάσεις",
    "suggestion_see_all_products": "Δείτε όλα τα προϊόντα αυτής της κατηγορίας:",
    "all_category_products": "Όλα τα Προϊόντα Κατηγορίας",
    "suggestion_try_removing_filters": "Δοκιμάστε να αφαιρέσετε μερικά φίλτρα:",
    "remove_a_filter": "Αφαίρεση φίλτρου",
    "suggestion_return_home": "Επιστρέψτε στην αρχική σελίδα:",
    "return_to_homepage": "Επιστροφή στην Αρχική",
    "no_subcategories": "Δεν υπάρχουν διαθέσιμες υποκατηγορίες.",
    "popular_categories": "Δημοφιλείς Κατηγορίες", "top_deals_in": "Top Προσφορές σε",
    "products_with_significant_price_drop": "Προϊόντα με σημαντική πτώση τιμής",
    "hottest_in": "Τα πιο Hot σε", "product_reviews_title": "Αξιολογήσεις Προϊόντων",
    "helpful_reviews_subtitle": "Χρήσιμες αξιολογήσεις από τους χρήστες μας",
    "popular_manufacturers": "Δημοφιλείς Κατασκευαστές",
    "price_alert_button": "Ειδοποίηση Πτώσης Τιμής",
    "price_alert_prompt_in": "Μην χάσετε ποτέ μια προσφορά για προϊόντα στην κατηγορία",
    "return_to": "Επιστροφή σε",
    "info_for_certified_store": "Πληροφορίες για πιστοποιημένο κατάστημα",
    "showing_products_from_store": "Εμφάνιση προϊόντων από το κατάστημα",
    "remove_filter": "Αφαίρεση αυτού του φίλτρου",
    "breadcrumbHome": "BestPrice",
    "breadcrumbAllProductsInCategory": "Όλα τα προϊόντα της κατηγορίας {{categoryName}}",
    "breadcrumbAllProductsAndSubcategoriesInCategory": "Όλα τα προϊόντα και οι υποκατηγορίες της κατηγορίας {{categoryName}}",
    "loadingProduct": "Φόρτωση Προϊόντος...",
    "addToShoppingList": "Προσθήκη στη Λίστα Αγορών", "addToComparison": "Προσθήκη στη σύγκριση",
    "iWantIt": "Το θέλω", "iHaveIt": "Το έχω",
    "notifyPriceDrop": "Ειδοποίηση για πτώση τιμής", "addToCollection": "Προσθήκη σε συλλογή",
    "priceFrom": "Από", "inStores": "σε {{count}} καταστήματα",
    "storesCount": "Καταστήματα ({{count}})",
    "available": "Διαθέσιμα", "nearMe": "Κοντά μου",
    "deliveryWithService": "Παράδοση με {{serviceName}}",
    "coupons": "Κουπόνια", "color": "Χρώμα",
    "officialResellers": "Επίσημοι μεταπωλητές", "priceHistoryTitle": "Ιστορικό Τιμών",
    "productDetails": "Λεπτομέρειες Προϊόντος", "userReviews": "Αξιολογήσεις Χρηστών ({{count}})",
    "questionsAndAnswers": "Ερωτήσεις & Απαντήσεις ({{count}})",
    "similarProducts": "Παρόμοια Προϊόντα", "dealsInCategory": "Προσφορές στην κατηγορία {{categoryName}}",
    "addToCart": "Προσθήκη στο Καλάθι", "buyNow": "Αγορά Τώρα",
    "specifications": "Χαρακτηριστικά", "reviews": "Αξιολογήσεις",
    "relatedProducts": "Σχετικά Προϊόντα", "writeReview": "Γράψτε Αξιολόγηση",
    "outOfStock": "Εξαντλημένο",
    "availableAt": "Διαθέσιμο σε {{count}} καταστήματα", "noStoresAvailable": "Προς το παρόν μη διαθέσιμο",
    "priceRange": "Εύρος Τιμών", "comparePrices": "Σύγκριση {{count}} Τιμών",
    "viewAllStores": "Δείτε όλα τα καταστήματα", "productDescription": "Περιγραφή",
    "share": "Κοινοποίηση", "removeFromFavorites": "Αφαίρεση από τα Αγαπημένα",
    "priceHistory": "Ιστορικό Τιμών",
    "certifiedStoresTooltip": "Εμφάνιση μόνο προϊόντων από πιστοποιημένα καταστήματα",
    "vendorPopupCertification": "Πιστοποίηση: {{certificationType}}",
    "vendorPopupInformation": "Πληροφορίες",
    "vendorPopupAddressNotAvailable": "Μόνο Ηλεκτρονικό κατάστημα",
    "vendorPopupPaymentMethods": "ΤΡΟΠΟΙ ΠΛΗΡΩΜΗΣ",
    "vendorPopupLearnMore": "Μάθε περισσότερα", "vendorPopupViewInStore": "Προβολή στο κατάστημα",
    "openingHoursNotAvailable": "Πληροφορίες ωραρίου μη διαθέσιμες",
    "closedToday": "Κλειστό σήμερα", "openUntil": "Ανοιχτό μέχρι τις {{time}}",
    "closedOpensAt": "Κλειστό - Ανοίγει στις {{time}}", "closedForToday": "Κλειστό για σήμερα",
    "openingHoursError": "Σφάλμα ωραρίου",
    "loginRequired": "Απαιτείται Σύνδεση",
    "loginToAddToFavorites": "Παρακαλώ συνδεθείτε για να προσθέσετε αυτό το προϊόν στα αγαπημένα σας",
    "productAddedToFavorites": "Το προϊόν {{productName}} προστέθηκε στα αγαπημένα",
    "linkCopied": "Ο Σύνδεσμος Αντιγράφηκε", "productLinkCopied": "Ο σύνδεσμος του προϊόντος αντιγράφηκε στο πρόχειρο",
    "copyFailed": "Η Αντιγραφή Απέτυχε", "couldNotCopyLink": " αδυναμία αντιγραφής συνδέσμου",
    "loginToSetPriceAlert": "Παρακαλώ συνδεθείτε για να ορίσετε ειδοποίηση τιμής",
    "loadingVendor": "Φόρτωση καταστήματος...", "allStores": "Καταστήματα",
    "certifiedStoreLinkText": "Πιστοποιημένο Κατάστημα ({{certificationLevel}})",
    "certifiedStoreFullText": "Το {{vendorName}} είναι πιστοποιημένο κατάστημα ({{certificationLevel}})",
    "memberSinceDate": "Στο BestPrice από {{date}}",
    "ratingTooltip": "{{rating}} αστέρια από {{count}} αξιολογήσεις",
    "social_facebook": "Facebook", "social_twitter": "Twitter", "social_instagram": "Instagram", "social_youtube": "YouTube", "social_linkedin": "LinkedIn", "social_tiktok": "TikTok",
    "additionalStores": "{{count}} ακόμη {{storeLabel}}",
    "storeLabelSingular": "κατάστημα", "storeLabelPlural": "καταστήματα",
    "logoFor": "Λογότυπο {{name}}", "screenshotFor": "Στιγμιότυπο {{name}}",
    "authorizedReseller": "Εξουσιοδοτημένος Μεταπωλητής", "previewWebsite": "Προεπισκόπηση Ιστοσελίδας",
    "dealsFromVendor": "Προσφορές από {{vendorName}}",
    "popularCategoriesInVendor": "Δημοφιλείς Κατηγορίες {{vendorName}}",
    "viewAllVendorProducts": "Δες όλα τα προϊόντα<span class=\"hide-mobile\"> του καταστήματος</span>",
    "storeReviewsTitle": "Αξιολογήσεις Καταστήματος {{vendorName}}",
    "reviewCount": "{{count}} αξιολογήσεις", "rateIt": "Αξιολόγησέ το",
    "reviewsPlaceholder": "(Προβολή αξιολογήσεων - Χρειάζεται Υλοποίηση)",
    "servicePointsTitle": "Σημεία Εξυπηρέτησης {{vendorName}}", "servicePointsCount": "{{count}} σημεία",
    "storeAndPickup": "Κατάστημα / Παραλαβή", "mapPlaceholderText": "Map Placeholder - Απαιτείται Βιβλιοθήκη Χάρτη",
    "noLanguagesInRegion": "Δεν υπάρχουν γλώσσες για αυτήν την περιοχή ακόμη.",
    "toggleTheme": "Εναλλαγή θέματος",
    "productsYouWant": "Προϊόντα που θέλεις", "productsYouHave": "Προϊόντα που έχεις",
    "myOffers": "Οι Προσφορές μου", "priceDrops": "Ειδοποιήσεις Τιμών",
    "myCollections": "Οι Συλλογές μου", "newCollection": "Νέα Συλλογή...",
    "creditsClub": "Credits Club", "savedOrders": "Αποθηκευμένες Παραγγελίες",
    "myQuestions": "Οι Ερωτήσεις μου", "myReviews": "Οι Αξιολογήσεις μου",
    "myFriends": "Οι Φίλοι μου", "viewProfileTooltip": "Δείτε το προφίλ σας",
    "userMenuCaretAlt": "Άνοιγμα μενού χρήστη",
    "backToTop": "Επιστροφή στην κορυφή",
    "bestpriceSloganShort": "Η πραγματικά καλύτερη τιμή",
    "bestpriceSloganLong": "Το BestPrice είναι η πρώτη και μεγαλύτερη υπηρεσία σύγκρισης τιμών στην Ελλάδα.",
    "bestpriceSloganFindDeals": "Στο BestPrice θα βρεις γρήγορα και εύκολα πραγματικές προσφορές και την καλύτερη τιμή από τα μεγαλύτερα καταστήματα.",
    "bestpriceGive": "BestPrice Give", "footerBestPriceSectionTitle": "BestPrice",
    "aboutUs": "Σχετικά με εμάς", "ourBlog": "Το Blog μας",
    "buyingGuides": "Οδηγοί αγοράς", "purchaseInsurance": "Ασφάλιση Αγορών",
    "advertising": "Διαφήμιση", "bestpriceCertification": "Πιστοποίηση BestPrice",
    "customerReviewAwards": "Customer Review Awards", "ourAwards": "Οι διακρίσεις μας",
    "ourTeam": "Η ομάδα μας", "bestpriceAssistant": "BestPrice Assistant",
    "jobOpenings": "Θέσεις εργασίας ({{count}})", "contactUs": "Επικοινωνία",
    "inNumbers": "Σε αριθμούς",
    "storeCountLink": "{{count}} καταστήματα", "productCountLink": "{{count}} προϊόντα",
    "brandCountLink": "{{count}} κατασκευαστές","dealCountLink": "{{count}} προσφορές",
    "termsAndPrivacy": "Όροι χρήσης & ιδιωτικότητα", "termsOfUse": "Όροι χρήσης",
    "privacyPolicy": "Πολιτική προσωπικών δεδομένων", "cookiePolicy": "Χρήση cookies",
    "gdprLink": "GDPR", "dsaLink": "DSA",
    "bestpriceForMerchants": "BestPrice For Merchants",
    "merchantsSectionSlogan1": "Έχεις ηλεκτρονικό κατάστημα;",
    "merchantsSectionSlogan2": "Δες πως το BestPrice μπορεί να σε βοηθήσει να αυξήσεις τις πωλήσεις σου!",
    "forMerchantsButton": "Για εμπόρους",
    "bestpriceForBrands": "BestPrice For Brands",
    "brandsSectionSlogan": "Το BestPrice for Brands θα προσφέρει χρήσιμες πληροφορίες & υπηρεσίες σε κατασκευαστές (Brands).",
    "moreInfoButton": "Περισσότερα",
    "bestpriceOnFacebook": "Το BestPrice στο Facebook", "bestpriceOnX": "Το BestPrice στο X",
    "bestpriceOnThreads": "Το BestPrice στο Threads", "bestpriceOnInstagram": "Το BestPrice στο Instagram",
    "bestpriceOnTikTok": "Το BestPrice στο TikTok", "bestpriceOnYouTube": "Το BestPrice στο YouTube",
    "bestpriceOnLinkedIn": "Το BestPrice στο LinkedIn",
    "homepageTitle": "Αρχική σελίδα",
    "changeLanguage": "Αλλαγή Γλώσσας", "selectYourLanguageTitle": "Επιλέξτε τη Γλώσσα σας",
    "suggestedLanguages": "Προτεινόμενες γλώσσες", "allLanguages": "Όλες οι γλώσσες",
    "languageCategoryEurope": "Ευρώπη", "languageCategoryAsia": "Ασία",
    "languageCategoryAmericas": "Αμερική", "languageCategoryAfrica": "Αφρική και Μέση Ανατολή",
    "languageCategoryEasternEurope": "Ανατολική Ευρώπη", "languageCategoryWesternEurope": "Δυτική Ευρώπη",
    "allBrands": "Όλες οι Μάρκες", "productsFromBrand": "Προϊόντα από {{brandName}}",
    "searchResultsFor": "Αποτελέσματα αναζήτησης για \"{{searchTerm}}\"",
    "noResultsFound": "Δεν βρέθηκαν αποτελέσματα για \"{{searchTerm}}\"",
    "sortBy": "Ταξινόμηση κατά", "viewAsGrid": "Προβολή Πλέγματος",
    "viewAsList": "Προβολή Λίστας", "itemsPerPage": "Αντικείμενα ανά σελίδα",
    "page": "Σελίδα", "of": "από", "nextPage": "Επόμενη", "previousPage": "Προηγούμενη",
    "todaysDeals": " σημερινές Προσφορές", "filterBy": "Φιλτράρισμα κατά",
    "shoppingCart": "Καλάθι Αγορών", "proceedToCheckout": "Ολοκλήρωση Παραγγελίας",
    "item": "Προϊόν", "quantity": "Ποσότητα", "subtotal": "Μερικό Σύνολο", "total": "Συνολικό Ποσό",
    "emptyCart": "Το καλάθι σας είναι άδειο.", "continueShopping": "Συνέχεια Αγορών",
    "shippingAddress": "Διεύθυνση Αποστολής", "billingAddress": "Διεύθυνση Χρέωσης",
    "paymentInformation": "Στοιχεία Πληρωμής", "placeOrder": "Καταχώρηση Παραγγελίας",
    "orderSummary": "Σύνοψη Παραγγελίας", "discountCode": "Κωδικός Έκπτωσης", "apply": "Εφαρμογή",
    "paymentMethod_credit_card": "Πιστωτική Κάρτα", "paymentMethod_bank_transfer": "Τραπεζική Κατάθεση",
    "paymentMethod_paypal": "PayPal", "paymentMethod_cash_on_delivery": "Αντικαταβολή",
    "paymentMethod_pickup_from_store": "Παραλαβή από το Κατάστημα", "paymentMethod_klarna": "Klarna",
    "paymentMethod_apple_pay": "Apple Pay", "paymentMethod_google_pay": "Google Pay",
    "paymentMethod_ideal": "iDEAL", "paymentMethod_crypto": "Κρυπτονόμισμα",
    "paymentMethod_pay_by_link": "Πληρωμή με Σύνδεσμο", "paymentMethod_pickup_via": "Παραλαβή μέσω Courier/Υπηρεσίας",
    'technology': 'Τεχνολογία', 'home-garden': 'Σπίτι & Κήπος', 'fashion': 'Μόδα',
    'health-beauty': 'Υγεία & Ομορφιά', 'kids-baby': 'Παιδικά - Βρεφικά', 'hobby-sports': 'Hobby, Αθλητισμός',
    'auto-moto': 'Μηχανοκίνηση',
    'mobile-telephony': 'Κινητή Τηλεφωνία', 'computers': 'Υπολογιστές', 'laptops-accessories': 'Laptops, Αξεσουάρ',
    'visual': 'Εικόνα', 'smartwatches-wearables': 'Smartwatches, Wearables', 'tablets-accessories': 'Tablets, Αξεσουάρ',
    'video-games': 'Video Games', 'audio': 'Ήχος', 'photo-video': 'Φωτογραφία, Video',
    'electronics': 'Ηλεκτρονικά', 'telephony': 'Τηλεφωνία', 'gadgets': 'Gadgets',
    'home-appliances': 'Οικιακές Συσκευές', 'tools': 'Εργαλεία', 'furniture': 'Έπιπλα',
    'garden': 'Κήπος', 'home-items': 'Είδη Σπιτιού', 'linens': 'Λευκά Είδη',
    'lighting': 'Φωτισμός', 'kitchenware': 'Είδη Κουζίνας', 'food-beverages': 'Τρόφιμα & Ποτά',
    'electrical-supplies': 'Ηλεκτρολογικά', 'smoking-accessories': 'Είδη Καπνιστού', 'office-supplies': 'Είδη Γραφείου',
    'gift-items': 'Είδη Δώρων', 'security-systems': 'Συστήματα Ασφαλείας', 'professional-equipment': 'Επαγγελματικός Εξοπλισμός',
    'seasonal-items': 'Εποχιακά Είδη', 'shopping-bags': 'Τσάντες για Ψώνια', 'shopping-trolleys': 'Καρότσια Λαϊκής',
    'church-items': 'Εκκλησιαστικά Είδη', 'pet-supplies': 'Είδη Κατοικιδίων', 'womens-fashion': 'Γυναικεία Μόδα',
    'mens-fashion': 'Ανδρική Μόδα', 'watches': 'Ρολόγια', 'jewelry': 'Κοσμήματα',
    'eyewear': 'Οπτικά', 'converse-all-star': 'Converse All Star', 'rain-umbrellas': 'Ομπρέλες Βροχής',
    'shoe-accessories': 'Αξεσουάρ Παπουτσιών', 'kids-baby-fashion': 'Παιδική, Βρεφική Μόδα', 'sneakers': 'Sneakers: Τα πιο trendy παπούτσια για κάθε στυλ και περίσταση!',
    'grooming': 'Περιποίηση', 'pharmacy-products': 'Είδη Φαρμακείου', 'perfumes': 'Αρώματα',
    'dietary-supplements': 'Συμπληρώματα Διατροφής','grooming-devices': 'Συσκευές Περιποίησης', 'makeup': 'Μακιγιάζ',
    'sunscreen-tanning': 'Αντηλιακή Προστασία, Μαύρισμα', 'medical-supplies': 'Ιατρικά Είδη', 'manicure-pedicure': 'Μανικιούρ - Πεντικιούρ',
    'oral-hygiene': 'Στοματική Υγιεινή', 'sex-toys': 'Sex Toys', 'firming-slimming': 'Σύσφιξη, Αδυνάτισμα',
    'cannabis-products': 'Προϊόντα Κάνναβης', 'orthopedics': 'Ορθοπεδικά', 'patient-aids': 'Βοηθήματα Ασθενών',
    'optics': 'Οπτικά', 'korean-cosmetics': 'Κορεάτικα Καλλυντικά', 'kids-toys': 'Παιδικά Παιχνίδια',
    'school-supplies': 'Σχολικά Είδη', 'baby-toys': 'Βρεφικά Παιχνίδια', 'baby-items': 'Βρεφικά Είδη',
    'kids-linens': 'Παιδικά Λευκά Είδη', 'christening-items': 'Βαπτιστικά', 'kids-watches': 'Παιδικά Ρολόγια',
    'sports': 'Αθλήματα', 'cycling': 'Ποδηλασία', 'leisure-time': 'Ελεύθερος Χρόνος',
    'fishing-diving': 'Ψάρεμα, Καταδύσεις', 'beach-sea-items': 'Είδη Θαλάσσης', 'camping': 'Camping',
    'travel-items-bags': 'Είδη Ταξιδίου, Τσάντες', 'books': 'Βιβλία', 'hunting': 'Κυνήγι',
    'fitness-equipment': 'Είδη Γυμναστικής', 'pet-supplies-hobby': 'Είδη Κατοικιδίων (Hobby)', 'drones-accessories': 'Drones & Αξεσουάρ',
    'electric-scooters': 'Ηλεκτρικά Πατίνια', 'hoverboards': 'Hoverboards', 'musical-instruments': 'Μουσικά Όργανα',
    'sports-accessories': 'Αξεσουάρ Αθλημάτων', 'exploration-items': 'Είδη Εξερεύνησης',
    'womens-sportswear': 'Γυναικεία Αθλητικά Ρούχα', 'womens-sports-shoes': 'Γυναικεία Αθλητικά Παπούτσια',
    'mens-sportswear': 'Ανδρικά Αθλητικά Ρούχα', 'mens-sports-shoes': 'Ανδρικά Αθλητικά Παπούτσια',
    'car': 'Αυτοκίνητο', 'motorcycle': 'Μοτοσυκλέτα', 'boat': 'Σκάφος',
    'truck-items': 'Είδη Φορτηγού', 'smartphones': 'Κινητά', 'iphone': 'iPhone',
    'mobile-cases': 'Θήκες Κινητών', 'bluetooth-handsfree': 'Bluetooth Handsfree', 'handsfree': 'Handsfree',
    'mobile-chargers': 'Φορτιστές Κινητών', 'tempered-glass': 'Tempered Glass', 'screen-protectors': 'Προστασία Οθόνης',
    'power-banks': 'Power Banks', 'mobile-batteries': 'Μπαταρίες Κινητών', 'selfie-sticks': 'Selfie Stick',
    'mobile-holders': 'Βάσεις Κινητού', 'charging-data-cables': 'Καλώδια Φόρτισης, Μεταφοράς Δεδομένων', 'anti-lost-trackers': 'Anti-Lost Tracker',
    'mobile-spare-parts': 'Ανταλλακτικά Κινητών', 'mobile-gimbals': 'Gimbal Κινητών', 'stylus-pens': 'Γραφίδες Αφής',
    'stylus-accessories': 'Αξεσουάρ Γραφίδας', 'bluetooth-headset-accessories': 'Αξεσουάρ Ακουστικών Bluetooth',
    'anti-lost-tracker-accessories': 'Αξεσουάρ Anti-Lost Tracker',
    'pop-sockets': 'Pop Sockets', 'mobile-tripods': 'Τρίποδα Κινητών', 'mobile-service-tools': 'Εργαλεία για Service Κινητών',
    'mobile-charms': 'Διακοσμητικά Κινητών', 'mobile-accessories': 'Αξεσουάρ Κινητών',
    'mobile-camera-protection': 'Προστασία Κάμερας Κινητών', 'mobile-camera-lenses': 'Φακοί Κάμερας Κινητών',
    'mobile-signal-boosters': 'Ενισχυτές Σήματος Κινητής Τηλεφωνίας', 'mobile-gaming-buttons': 'Πλήκτρα Mobile Gaming',
    'connection-packs': 'Πακέτα Σύνδεσης', 'portable-bluetooth-speakers-mobile': 'Φορητά Ηχεία Bluetooth',
    'ps5-games': 'PS5 Games', 'pc-games': 'PC Games', 'amplifiers-preamplifiers': 'Ενισχυτές, Προενισχυτές',
    'hi-fi-systems': 'Συστήματα Hi-Fi',
  },
  // ============================ Spanish (es) - Placeholder, needs full translation ============================
  es: {
    email: 'Correo electrónico', password: 'Contraseña', forgotPassword: '¿Olvidaste tu contraseña?', register: 'Registrarse',
    signIn: 'Iniciar sesión', loggingIn: 'Iniciando sesión...', emailPlaceholder: 'email@example.com', orContinueWith: 'O continuar con',
    google: 'Google', facebook: 'Facebook', twitter: 'Twitter', createAccount: 'Crear cuenta',
    dontHaveAccount: "¿No tienes una cuenta?", alreadyHaveAccount: '¿Ya tienes una cuenta?', fullName: 'Nombre Completo', confirmPassword: 'Confirmar Contraseña',
    agreeToTerms: 'Acepto los Términos de Servicio y la Política de Privacidad',
    creatingAccount: 'Creando cuenta...', resetYourPassword: 'Restablecer Tu Contraseña',
    enterEmailForReset: 'Introduce tu dirección de correo electrónico y te enviaremos un enlace para restablecer tu contraseña.',
    sendResetLink: 'Enviar Enlace de Restablecimiento', sendingResetLink: 'Enviando...',
    resetPasswordEmailSent: 'Correo electrónico de restablecimiento de contraseña enviado. Por favor, revisa tu bandeja de entrada.',
    backToLogin: 'Volver a Iniciar Sesión', createNewPassword: 'Crear Nueva Contraseña',
    newPassword: 'Nueva Contraseña', updatePassword: 'Actualizar Contraseña',
    updating: 'Actualizando...', passwordUpdated: 'Contraseña Actualizada',
    passwordSuccessfullyChanged: 'Tu contraseña ha sido cambiada exitosamente.',
    passwordResetFailed: 'Error al Restablecer la Contraseña',
    errorProcessingRequest: 'Hubo un error procesando tu solicitud.',
    passwordTooShort: 'Contraseña Demasiado Corta', passwordMinLength: 'La contraseña debe tener al menos 6 caracteres.',
    passwordsDontMatch: 'Las Contraseñas no Coinciden', pleaseCheckPasswords: 'Por favor, verifica que ambas contraseñas coincidan.',
    languageSettings: 'Configuración de Idioma', selectLanguage: 'Seleccionar Idioma', english: 'Inglés', greek: 'Griego',
    spanish: 'Español', french: 'Francés', german: 'Alemán', systemLanguage: 'Idioma del Sistema (Predeterminado)',
    save: 'Guardar', cancel: 'Cancelar', loading: 'Cargando...', success: 'Éxito',
    error: 'Error', wallet: 'Cartera', myWallet: 'Mi Cartera', manageWallet: 'Gestiona tus fondos, transacciones y pagos de anuncios',
    deposit: 'Depositar', transactions: 'Transacciones', connectWallet: 'Conectar Cartera', addFunds: 'Añadir Fondos',
    amount: 'Cantidad ($)', enterAmount: 'Introducir cantidad', paymentMethod: 'Método de Pago', processing: 'Procesando...',
    myAccount: 'Mi Cuenta', profile: 'Perfil', favorites: 'Favoritos', recentlyViewed: 'Visto Recientemente',
    priceAlerts: 'Alertas de Precio', settings: 'Configuración', logout: 'Cerrar Sesión', myProfile: 'Mi Perfil',
    managePersonalInfo: 'Gestionar tu información personal',
    name: 'Nombre', memberSince: 'Miembro desde', role: 'Rol', administrator: 'Administrador',
    regularUser: 'Usuario Regular', editProfile: 'Editar Perfil', accountSummary: 'Resumen de Cuenta', categories: 'Categorías',
    gifts: 'Regalos', deals: 'Ofertas', clearFilters: 'Limpiar filtros', finalPrice: 'Precio final',
    yes: "Sí", no: "No", ok: "OK", close: "Cerrar",
    showMore: "Mostrar Más", showLess: "Mostrar Menos", all: "Todo", selectOption: "Selecciona una opción",
    optional: "Opcional", required: "Requerido", back: "Atrás", next: "Siguiente",
    submit: "Enviar", search: "Buscar", searchPlaceholder: "Buscar productos...",
    notFoundPageTitle: "Página No Encontrada", notFoundMessage: "¡Ups! La página que buscas no existe.",
    recently_viewed_title: "Visto Recientemente",
    "product_singular": "producto", "product_plural": "{{count}} productos",
    "rating_label": "Clasificación", "reviews_label_singular": "reseña", "reviews_label_plural": "{{count}} reseñas",
    "from_vendor": "de", "with": "con",
    "no_products_in_category": "Aún no hay productos en esta categoría.",
    "filters_title": "Filtros", "remove_all_filters_tooltip": "Eliminar todos los filtros",
    "show_only_title": "Mostrar solo", "deals_label": "Ofertas",
    "deals_title": "Productos con bajada de precio significativa",
    "certified_label": "Certificado", "certified_stores_title": "Tiendas Certificadas",
    "instock_label": "En Stock", "instock_title": "Solo productos disponibles en stock",
    "boxnow_delivery_title": "Entrega BOX NOW",
    "boxnow_tooltip": "Recoge tu pedido en un casillero BOX NOW 24/7",
    "delivery_label": "BOX NOW", "manufacturer_title": "Fabricante",
    "show_less_manufacturers": "Mostrar menos fabricantes", "show_all_manufacturers": "Mostrar todos los fabricantes",
    "show_all": "Mostrar Todo",
    "show_less_options": "Mostrar menos opciones para", "show_all_options": "Mostrar todas las opciones para",
    "remove_instock_filter": "Eliminar filtro 'En Stock'", "remove_deals_filter": "Eliminar filtro 'Ofertas'",
    "remove_certified_filter": "Eliminar filtro 'Certificado'", "remove_nearby_filter": "Eliminar filtro 'Cercano'",
    "remove_boxnow_filter": "Eliminar filtro 'BOX NOW'",
    "remove_brand_filter": "Eliminar filtro de marca", "remove_spec_filter": "Eliminar filtro de especificación",
    "reset_all_filters": "Restablecer todos los filtros", "clear_all_filters": "Limpiar Todo",
    "selected_deals": "Ofertas Seleccionadas", "popular_choices": "Opciones Populares",
    "sort_most_popular": "Más Populares", "sort_newest": "Más Nuevos",
    "sort_cheapest": "Más Baratos", "sort_most_expensive": "Más Caros",
    "sort_alphabetical": "Alfabético (A-Z)", "sort_most_reviews": "Más Reseñas",
    "sort_by_manufacturer": "Por Fabricante", "sort_num_stores": "Número de Tiendas",
    "price_alert_for": "Alerta de Precio para",
    "no_products_found_filters": "Ningún producto coincide con tus filtros actuales.",
    "suggestions_title": "Sugerencias",
    "suggestion_see_all_products": "Ver todos los productos en esta categoría:",
    "all_category_products": "Todos los Productos de la Categoría",
    "suggestion_try_removing_filters": "Intenta eliminar algunos filtros:",
    "remove_a_filter": "Eliminar un filtro",
    "suggestion_return_home": "Volver a la página de inicio:",
    "return_to_homepage": "Volver a la Página de Inicio",
    "no_subcategories": "No hay subcategorías disponibles.",
    "popular_categories": "Categorías Populares", "top_deals_in": "Mejores Ofertas en",
    "products_with_significant_price_drop": "Productos con una bajada de precio significativa",
    "hottest_in": "Lo Más Popular en", "product_reviews_title": "Reseñas de Productos",
    "helpful_reviews_subtitle": "Reseñas útiles de nuestros usuarios",
    "popular_manufacturers": "Fabricantes Populares",
    "price_alert_button": "Establecer Alerta de Precio",
    "price_alert_prompt_in": "No te pierdas una oferta para productos en",
    "return_to": "Volver a",
    "info_for_certified_store": "Información para tienda certificada",
    "showing_products_from_store": "Mostrando productos de la tienda",
    "remove_filter": "Eliminar este filtro",
    "breadcrumbHome": "BestPrice", 
    "breadcrumbAllProductsInCategory": "Todos los productos de la categoría {{categoryName}}",
    "breadcrumbAllProductsAndSubcategoriesInCategory": "Todos los productos y subcategorías de la categoría {{categoryName}}",
    "loadingProduct": "Cargando Producto...",
    "addToShoppingList": "Añadir a la Lista de Compras", "addToComparison": "Añadir a Comparación",
    "iWantIt": "Lo Quiero", "iHaveIt": "Lo Tengo",
    "notifyPriceDrop": "Notificarme si baja el precio", "addToCollection": "Añadir a Colección",
    "priceFrom": "Desde", "inStores": "en {{count}} tiendas",
    "storesCount": "Tiendas ({{count}})",
    "available": "Disponible", "nearMe": "Cerca de mí",
    "deliveryWithService": "Entrega con {{serviceName}}",
    "coupons": "Cupones", "color": "Color",
    "officialResellers": "Vendedores Oficiales", "priceHistoryTitle": "Historial de Precios",
    "productDetails": "Detalles del Producto", "userReviews": "Reseñas de Usuarios ({{count}})",
    "questionsAndAnswers": "Preguntas y Respuestas ({{count}})",
    "similarProducts": "Productos Similares", "dealsInCategory": "Ofertas en {{categoryName}}",
    "addToCart": "Añadir al Carrito", "buyNow": "Comprar Ahora",
    "specifications": "Especificaciones", "reviews": "Reseñas",
    "relatedProducts": "Productos Relacionados", "writeReview": "Escribir una Reseña",
    "outOfStock": "Agotado",
    "availableAt": "Disponible en {{count}} tiendas", "noStoresAvailable": "Actualmente no disponible",
    "priceRange": "Rango de Precios", "comparePrices": "Comparar {{count}} Precios",
    "viewAllStores": "Ver todas las tiendas", "productDescription": "Descripción",
    "share": "Compartir", "addToFavorites": "Añadir a Favoritos",
    "removeFromFavorites": "Eliminar de Favoritos", "priceHistory": "Historial de Precios",
    "certifiedStoresTooltip": "Mostrar solo productos de tiendas certificadas",
    "vendorPopupCertification": "Certificación: {{certificationType}}",
    "vendorPopupInformation": "Información", "vendorPopupAddressNotAvailable": "Solo Tienda Online",
    "vendorPopupPaymentMethods": "MÉTODOS DE PAGO",
    "vendorPopupLearnMore": "Saber Más", "vendorPopupViewInStore": "Ver en Tienda",
    "openingHoursNotAvailable": "Información de horario no disponible",
    "closedToday": "Cerrado hoy", "openUntil": "Abierto hasta las {{time}}",
    "closedOpensAt": "Cerrado - Abre a las {{time}}", "closedForToday": "Cerrado por hoy",
    "openingHoursError": "Error en el horario",
    "loginRequired": "Se Requiere Iniciar Sesión",
    "loginToAddToFavorites": "Por favor, inicia sesión para añadir este producto a tus favoritos",
    "productAddedToFavorites": "{{productName}} ha sido añadido a tus favoritos",
    "linkCopied": "Enlace Copiado", "productLinkCopied": "Enlace del producto copiado al portapapeles",
    "copyFailed": "Error al Copiar", "couldNotCopyLink": "No se pudo copiar el enlace",
    "loginToSetPriceAlert": "Por favor, inicia sesión para establecer una alerta de precio",
    "loadingVendor": "Cargando tienda...", "allStores": "Tiendas",
    "certifiedStoreLinkText": "Tienda Certificada ({{certificationLevel}})",
    "certifiedStoreFullText": "{{vendorName}} es una tienda certificada ({{certificationLevel}})",
    "memberSinceDate": "En BestPrice desde {{date}}",
    "ratingTooltip": "{{rating}} estrellas de {{count}} valoraciones",
    "social_facebook": "Facebook", "social_twitter": "Twitter", "social_instagram": "Instagram", "social_youtube": "YouTube", "social_linkedin": "LinkedIn", "social_tiktok": "TikTok",
    "additionalStores": "{{count}} más {{storeLabel}}",
    "storeLabelSingular": "tienda", "storeLabelPlural": "tiendas",
    "logoFor": "Logo de {{name}}", "screenshotFor": "Captura de pantalla de {{name}}",
    "authorizedReseller": "Distribuidor Autorizado", "previewWebsite": "Vista Previa del Sitio Web",
    "dealsFromVendor": "Ofertas de {{vendorName}}",
    "popularCategoriesInVendor": "Categorías Populares en {{vendorName}}",
    "viewAllVendorProducts": "Ver todos los productos<span class=\"hide-mobile\"> de la tienda</span>",
    "storeReviewsTitle": "Reseñas de la Tienda {{vendorName}}",
    "reviewCount": "{{count}} reseñas", "rateIt": "Califícalo",
    "reviewsPlaceholder": "(Visualización de reseñas - Implementación necesaria)",
    "servicePointsTitle": "Puntos de Servicio {{vendorName}}", "servicePointsCount": "{{count}} puntos",
    "storeAndPickup": "Tienda / Punto de Recogida", "mapPlaceholderText": "Marcador de Posición del Mapa - Requiere Biblioteca de Mapas",
    "noLanguagesInRegion": "No hay idiomas listados para esta región todavía.",
    "toggleTheme": "Cambiar tema",
    "productsYouWant": "Productos que quieres", "productsYouHave": "Productos que tienes",
    "myOffers": "Mis Ofertas", "priceDrops": "Alertas de Precio",
    "myCollections": "Mis Colecciones", "newCollection": "Nueva Colección...",
    "creditsClub": "Club de Créditos", "savedOrders": "Pedidos Guardados",
    "myQuestions": "Mis Preguntas", "myReviews": "Mis Reseñas",
    "myFriends": "Mis Amigos", "viewProfileTooltip": "Ver tu perfil",
    "userMenuCaretAlt": "Abrir menú de usuario",
    "backToTop": "Volver Arriba",
    "bestpriceSloganShort": "El precio verdaderamente mejor",
    "bestpriceSloganLong": "BestPrice es el primer y más grande servicio de comparación de precios en España.",
    "bestpriceSloganFindDeals": "En BestPrice encontrarás rápida y fácilmente ofertas reales y el mejor precio de las tiendas más grandes.",
    "bestpriceGive": "BestPrice Give", "footerBestPriceSectionTitle": "BestPrice",
    "aboutUs": "Sobre Nosotros", "ourBlog": "Nuestro Blog",
    "buyingGuides": "Guías de Compra", "purchaseInsurance": "Seguro de Compra",
    "advertising": "Publicidad", "bestpriceCertification": "Certificación BestPrice",
    "customerReviewAwards": "Premios de Reseñas de Clientes", "ourAwards": "Nuestros Premios",
    "ourTeam": "Nuestro Equipo", "bestpriceAssistant": "Asistente BestPrice",
    "jobOpenings": "Ofertas de Empleo ({{count}})", "contactUs": "Contacto",
    "inNumbers": "En Cifras",
    "storeCountLink": "{{count}} tiendas", "productCountLink": "{{count}} productos",
    "brandCountLink": "{{count}} fabricantes","dealCountLink": "{{count}} ofertas",
    "termsAndPrivacy": "Términos y Privacidad", "termsOfUse": "Términos de Uso",
    "privacyPolicy": "Política de Privacidad", "cookiePolicy": "Política de Cookies",
    "gdprLink": "RGPD", "dsaLink": "LSD",
    "bestpriceForMerchants": "BestPrice Para Comerciantes",
    "merchantsSectionSlogan1": "¿Tienes una tienda online?",
    "merchantsSectionSlogan2": "¡Descubre cómo BestPrice puede ayudarte a aumentar tus ventas!",
    "forMerchantsButton": "Para Comerciantes",
    "bestpriceForBrands": "BestPrice Para Marcas",
    "brandsSectionSlogan": "BestPrice para Marcas ofrecerá información y servicios útiles a los fabricantes (Marcas).",
    "moreInfoButton": "Más Información",
    "bestpriceOnFacebook": "BestPrice en Facebook", "bestpriceOnX": "BestPrice en X",
    "bestpriceOnThreads": "BestPrice en Threads", "bestpriceOnInstagram": "BestPrice en Instagram",
    "bestpriceOnTikTok": "BestPrice en TikTok", "bestpriceOnYouTube": "BestPrice en YouTube",
    "bestpriceOnLinkedIn": "BestPrice en LinkedIn",
    "homepageTitle": "Página de Inicio",
    "changeLanguage": "Cambiar Idioma", "selectYourLanguageTitle": "Selecciona tu Idioma",
    "suggestedLanguages": "Idiomas sugeridos", "allLanguages": "Todos los idiomas",
    "languageCategoryEurope": "Europa", "languageCategoryAsia": "Asia",
    "languageCategoryAmericas": "Américas", "languageCategoryAfrica": "África y Medio Oriente",
    "languageCategoryEasternEurope": "Europa del Este", "languageCategoryWesternEurope": "Europa Occidental",
    "allBrands": "Todas las Marcas", "productsFromBrand": "Productos de {{brandName}}",
    "searchResultsFor": "Resultados de búsqueda para \"{{searchTerm}}\"",
    "noResultsFound": "No se encontraron resultados para \"{{searchTerm}}\"",
    "sortBy": "Ordenar por", "viewAsGrid": "Vista de Cuadrícula",
    "viewAsList": "Vista de Lista", "itemsPerPage": "Artículos por página",
    "page": "Página", "of": "de", "nextPage": "Siguiente", "previousPage": "Anterior",
    "todaysDeals": "Ofertas de Hoy", "filterBy": "Filtrar por",
    "shoppingCart": "Carrito de Compras", "proceedToCheckout": "Proceder al Pago",
    "item": "Artículo", "quantity": "Cantidad", "subtotal": "Subtotal", "total": "Total",
    "emptyCart": "Tu carrito está vacío.", "continueShopping": "Continuar Comprando",
    "shippingAddress": "Dirección de Envío", "billingAddress": "Dirección de Facturación",
    "paymentInformation": "Información de Pago", "placeOrder": "Realizar Pedido",
    "orderSummary": "Resumen del Pedido", "discountCode": "Código de Descuento", "apply": "Aplicar",
    "paymentMethod_credit_card": "Tarjeta de Crédito", "paymentMethod_bank_transfer": "Transferencia Bancaria",
    "paymentMethod_paypal": "PayPal", "paymentMethod_cash_on_delivery": "Contra Reembolso",
    "paymentMethod_pickup_from_store": "Recoger en Tienda", "paymentMethod_klarna": "Klarna",
    "paymentMethod_apple_pay": "Apple Pay", "paymentMethod_google_pay": "Google Pay",
    "paymentMethod_ideal": "iDEAL", "paymentMethod_crypto": "Criptomoneda",
    "paymentMethod_pay_by_link": "Pagar con Enlace", "paymentMethod_pickup_via": "Recoger vía Mensajería/Servicio",
    'technology': 'Tecnología', 'home-garden': 'Casa y Jardín', 'fashion': 'Moda',
    'health-beauty': 'Salud y Belleza', 'kids-baby': 'Niños y Bebés', 'hobby-sports': 'Aficiones y Deportes',
    'auto-moto': 'Automoción', 'mobile-telephony': 'Telefonía Móvil', 'computers': 'Ordenadores',
    'laptops-accessories': 'Portátiles y Accesorios', 'visual': 'Imagen',
    'smartwatches-wearables': 'Smartwatches y Wearables', 'tablets-accessories': 'Tablets y Accesorios',
    'video-games': 'Videojuegos', 'audio': 'Audio', 'photo-video': 'Foto y Vídeo',
    'electronics': 'Electrónica', 'telephony': 'Telefonía', 'gadgets': 'Gadgets',
    'home-appliances': "Electrodomésticos", 'tools': "Herramientas", 'furniture': "Muebles",
    'garden': "Jardín", 'home-items': "Artículos para el hogar", 'linens': "Ropa de cama y mesa",
    'lighting': "Iluminación", 'kitchenware': "Utensilios de cocina", 'food-beverages': "Alimentos y Bebidas",
    'electrical-supplies': "Materiales eléctricos", 'smoking-accessories': "Accesorios para fumadores", 'office-supplies': "Material de oficina",
    'gift-items': "Artículos de regalo", 'security-systems': "Sistemas de seguridad", 'professional-equipment': "Equipamiento profesional",
    'seasonal-items': "Artículos de temporada", 'shopping-bags': "Bolsas de compra", 'shopping-trolleys': "Carritos de compra",
    'church-items': "Artículos religiosos", 'pet-supplies': "Suministros para mascotas", 'womens-fashion': "Moda Femenina",
    'mens-fashion': "Moda Masculina", 'watches': "Relojes", 'jewelry': "Joyería",
    'eyewear': "Gafas", 'converse-all-star': "Converse All Star", 'rain-umbrellas': "Paraguas",
    'shoe-accessories': "Accesorios para calzado", 'kids-baby-fashion': "Moda Infantil y Bebé", 'sneakers': "Zapatillas deportivas",
    'grooming': "Cuidado Personal", 'pharmacy-products': "Productos de Farmacia", 'perfumes': "Perfumes",
    'dietary-supplements': "Suplementos Alimenticios",'grooming-devices': "Aparatos de Cuidado Personal", 'makeup': "Maquillaje",
    'sunscreen-tanning': "Protección Solar y Bronceado", 'medical-supplies': "Suministros Médicos", 'manicure-pedicure': "Manicura y Pedicura",
    'oral-hygiene': "Higiene Bucal", 'sex-toys': "Juguetes Sexuales", 'firming-slimming': "Reafirmantes y Adelgazantes",
    'cannabis-products': "Productos de Cannabis", 'orthopedics': "Ortopedia", 'patient-aids': "Ayudas para Pacientes",
    'optics': "Óptica", 'korean-cosmetics': "Cosmética Coreana", 'kids-toys': "Juguetes para Niños",
    'school-supplies': "Material Escolar", 'baby-toys': "Juguetes para Bebés", 'baby-items': "Artículos para Bebés",
    'kids-linens': "Ropa de Cama Infantil", 'christening-items': "Artículos de Bautizo", 'kids-watches': "Relojes para Niños",
    'sports': "Deportes", 'cycling': "Ciclismo", 'leisure-time': "Tiempo Libre",
    'fishing-diving': "Pesca y Buceo", 'beach-sea-items': "Artículos de Playa y Mar", 'camping': "Camping",
    'travel-items-bags': "Artículos de Viaje y Bolsos", 'books': "Libros", 'hunting': "Caza",
    'fitness-equipment': "Equipamiento de Fitness", 'pet-supplies-hobby': "Suministros para Mascotas (Hobby)", 'drones-accessories': "Drones y Accesorios",
    'electric-scooters': "Patinetes Eléctricos", 'hoverboards': "Hoverboards", 'musical-instruments': "Instrumentos Musicales",
    'sports-accessories': "Accesorios Deportivos", 'exploration-items': "Artículos de Exploración",
    'womens-sportswear': "Ropa Deportiva Femenina", 'womens-sports-shoes': "Zapatillas Deportivas Femeninas",
    'mens-sportswear': "Ropa Deportiva Masculina", 'mens-sports-shoes': "Zapatillas Deportivas Masculinas",
    'car': "Coche", 'motorcycle': "Motocicleta", 'boat': "Barco",
    'truck-items': "Artículos para Camión", 'smartphones': "Smartphones", 'iphone': "iPhone",
    'mobile-cases': "Fundas para Móviles", 'bluetooth-handsfree': "Manos Libres Bluetooth", 'handsfree': "Manos Libres",
    'mobile-chargers': "Cargadores para Móviles", 'tempered-glass': "Cristal Templado", 'screen-protectors': "Protectores de Pantalla",
    'power-banks': "Baterías Externas", 'mobile-batteries': "Baterías para Móviles", 'selfie-sticks': "Palos Selfie",
    'mobile-holders': "Soportes para Móviles", 'charging-data-cables': "Cables de Carga y Datos", 'anti-lost-trackers': "Localizadores Anti-Pérdida",
    'mobile-spare-parts': "Repuestos para Móviles", 'mobile-gimbals': "Gimbals para Móviles", 'stylus-pens': "Lápices Táctiles",
    'stylus-accessories': "Accesorios para Lápices Táctiles", 'bluetooth-headset-accessories': "Accesorios para Auriculares Bluetooth",
    'anti-lost-tracker-accessories': "Accesorios para Localizadores Anti-Pérdida",
    'pop-sockets': "PopSockets", 'mobile-tripods': "Trípodes para Móviles", 'mobile-service-tools': "Herramientas de Servicio para Móviles",
    'mobile-charms': "Colgantes para Móviles", 'mobile-accessories': "Accesorios para Móviles",
    'mobile-camera-protection': "Protección de Cámara para Móviles", 'mobile-camera-lenses': "Lentes de Cámara para Móviles",
    'mobile-signal-boosters': "Amplificadores de Señal Móvil", 'mobile-gaming-buttons': "Botones de Juego para Móviles",
    'connection-packs': "Paquetes de Conexión", 'portable-bluetooth-speakers-mobile': "Altavoces Bluetooth Portátiles (Móvil)",
    'ps5-games': "Juegos PS5", 'pc-games': "Juegos PC", 'amplifiers-preamplifiers': "Amplificadores y Preamplificadores",
    'hi-fi-systems': "Sistemas Hi-Fi",
  },
  // ============================ French (fr) - Placeholder, needs full translation =============================
  fr: {
    email: 'E-mail', password: 'Mot de passe', signIn: 'Connexion', createAccount: 'Créer un compte',
    // ... (Rest of your French translations, ensuring all new keys from 'en' and 'el' are added and translated)
    "product_singular": "produit", "product_plural": "{{count}} produits",
    "rating_label": "Évaluation", "reviews_label_singular": "avis", "reviews_label_plural": "{{count}} avis",
    "from_vendor": "de", "with": "avec",
    "loadingVendor": "Chargement du magasin...", "allStores": "Magasins",
    "certifiedStoreLinkText": "Magasin Certifié ({{certificationLevel}})",
    "certifiedStoreFullText": "{{vendorName}} est un magasin certifié ({{certificationLevel}})",
    "memberSinceDate": "Sur BestPrice depuis {{date}}",
    "ratingTooltip": "{{rating}} étoiles sur {{count}} évaluations",
    "social_facebook": "Facebook", "social_twitter": "Twitter", "social_instagram": "Instagram", "social_youtube": "YouTube", "social_linkedin": "LinkedIn", "social_tiktok": "TikTok",
    "additionalStores": "{{count}} autre(s) {{storeLabel}}",
    "storeLabelSingular": "magasin", "storeLabelPlural": "magasins",
    "logoFor": "Logo de {{name}}", "screenshotFor": "Capture d'écran de {{name}}",
    "authorizedReseller": "Revendeur Agréé", "previewWebsite": "Aperçu du Site Web",
    "dealsFromVendor": "Offres de {{vendorName}}",
    "popularCategoriesInVendor": "Catégories Populaires chez {{vendorName}}",
    "viewAllVendorProducts": "Voir tous les produits<span class=\"hide-mobile\"> du magasin</span>",
    "storeReviewsTitle": "Avis sur le Magasin {{vendorName}}",
    "reviewCount": "{{count}} avis", "rateIt": "Évaluez-le",
    "reviewsPlaceholder": "(Affichage des avis - Implémentation nécessaire)",
    "servicePointsTitle": "Points de Service {{vendorName}}", "servicePointsCount": "{{count}} points",
    "storeAndPickup": "Magasin / Point de Retrait", "mapPlaceholderText": "Espace réservé pour la carte - Nécessite une bibliothèque de cartes",
    "noLanguagesInRegion": "Aucune langue répertoriée pour cette région pour le moment.",
    "toggleTheme": "Changer de thème",
    "productsYouWant": "Produits souhaités", "productsYouHave": "Produits possédés",
    "myOffers": "Mes Offres", "priceDrops": "Alertes de Prix",
    "myCollections": "Mes Collections", "newCollection": "Nouvelle Collection...",
    "creditsClub": "Club de Crédits", "savedOrders": "Commandes Enregistrées",
    "myQuestions": "Mes Questions", "myReviews": "Mes Avis",
    "myFriends": "Mes Amis", "viewProfileTooltip": "Voir votre profil",
    "userMenuCaretAlt": "Ouvrir le menu utilisateur",
    "backToTop": "Retour en Haut",
    "bestpriceSloganShort": "Le meilleur prix, vraiment",
    "bestpriceSloganLong": "BestPrice est le premier et le plus grand service de comparaison de prix en France.",
    "bestpriceSloganFindDeals": "Sur BestPrice, vous trouverez rapidement et facilement de vraies offres et le meilleur prix des plus grands magasins.",
    "bestpriceGive": "BestPrice Give", "footerBestPriceSectionTitle": "BestPrice",
    "aboutUs": "À Propos de Nous", "ourBlog": "Notre Blog",
    "buyingGuides": "Guides d'Achat", "purchaseInsurance": "Assurance Achat",
    "advertising": "Publicité", "bestpriceCertification": "Certification BestPrice",
    "customerReviewAwards": "Prix des Avis Clients", "ourAwards": "Nos Récompenses",
    "ourTeam": "Notre Équipe", "bestpriceAssistant": "Assistant BestPrice",
    "jobOpenings": "Offres d'Emploi ({{count}})", "contactUs": "Contact",
    "inNumbers": "En Chiffres",
    "storeCountLink": "{{count}} magasins", "productCountLink": "{{count}} produits",
    "brandCountLink": "{{count}} fabricants","dealCountLink": "{{count}} offres",
    "termsAndPrivacy": "Termes & Confidentialité", "termsOfUse": "Conditions d'Utilisation",
    "privacyPolicy": "Politique de Confidentialité", "cookiePolicy": "Politique de Cookies",
    "gdprLink": "RGPD", "dsaLink": "LSD",
    "bestpriceForMerchants": "BestPrice Pour Commerçants",
    "merchantsSectionSlogan1": "Avez-vous une boutique en ligne ?",
    "merchantsSectionSlogan2": "Découvrez comment BestPrice peut vous aider à augmenter vos ventes !",
    "forMerchantsButton": "Pour Commerçants",
    "bestpriceForBrands": "BestPrice Pour Marques",
    "brandsSectionSlogan": "BestPrice pour Marques offrira des informations et services utiles aux fabricants (Marques).",
    "moreInfoButton": "Plus d'Infos",
    "bestpriceOnFacebook": "BestPrice sur Facebook", "bestpriceOnX": "BestPrice sur X",
    "bestpriceOnThreads": "BestPrice sur Threads", "bestpriceOnInstagram": "BestPrice sur Instagram",
    "bestpriceOnTikTok": "BestPrice sur TikTok", "bestpriceOnYouTube": "BestPrice sur YouTube",
    "bestpriceOnLinkedIn": "BestPrice sur LinkedIn",
    "homepageTitle": "Page d'Accueil",
    "changeLanguage": "Changer de Langue", "selectYourLanguageTitle": "Sélectionnez Votre Langue",
    "suggestedLanguages": "Langues suggérées", "allLanguages": "Toutes les langues",
    "languageCategoryEurope": "Europe", "languageCategoryAsia": "Asie",
    "languageCategoryAmericas": "Amériques", "languageCategoryAfrica": "Afrique et Moyen-Orient",
    "languageCategoryEasternEurope": "Europe de l'Est", "languageCategoryWesternEurope": "Europe de l'Ouest",
    // ... (All other keys from 'en'/'el' translated to 'fr')
    'technology': 'Technologie', 'home-garden': 'Maison et Jardin', // ... ALL CATEGORY SLUGS ...
  },
  // ============================ German (de) - Placeholder, needs full translation =============================
  de: {
    email: 'E-Mail', password: 'Passwort', signIn: 'Anmelden', createAccount: 'Konto erstellen',
    // ... (Rest of your German translations, ensuring all new keys from 'en' and 'el' are added and translated)
    "product_singular": "Produkt", "product_plural": "{{count}} Produkte",
    "rating_label": "Bewertung", "reviews_label_singular": "Bewertung", "reviews_label_plural": "{{count}} Bewertungen",
    "from_vendor": "von", "with": "mit",
    "loadingVendor": "Shop wird geladen...", "allStores": "Shops",
    "certifiedStoreLinkText": "Zertifizierter Shop ({{certificationLevel}})",
    "certifiedStoreFullText": "{{vendorName}} ist ein zertifizierter Shop ({{certificationLevel}})",
    "memberSinceDate": "Bei BestPrice seit {{date}}",
    "ratingTooltip": "{{rating}} Sterne von {{count}} Bewertungen",
    "social_facebook": "Facebook", "social_twitter": "Twitter", "social_instagram": "Instagram", "social_youtube": "YouTube", "social_linkedin": "LinkedIn", "social_tiktok": "TikTok",
    "additionalStores": "{{count}} weitere {{storeLabel}}",
    "storeLabelSingular": "Shop", "storeLabelPlural": "Shops",
    "logoFor": "{{name}} Logo", "screenshotFor": "{{name}} Screenshot",
    "authorizedReseller": "Autorisierter Händler", "previewWebsite": "Webseite Vorschau",
    "dealsFromVendor": "Angebote von {{vendorName}}",
    "popularCategoriesInVendor": "Beliebte Kategorien bei {{vendorName}}",
    "viewAllVendorProducts": "Alle Produkte<span class=\"hide-mobile\"> des Shops anzeigen</span>",
    "storeReviewsTitle": "Shop-Bewertungen für {{vendorName}}",
    "reviewCount": "{{count}} Bewertungen", "rateIt": "Bewerten",
    "reviewsPlaceholder": "(Bewertungsanzeige - Implementierung erforderlich)",
    "servicePointsTitle": "Servicestellen {{vendorName}}", "servicePointsCount": "{{count}} Stellen",
    "storeAndPickup": "Shop / Abholstelle", "mapPlaceholderText": "Kartenplatzhalter - Kartenbibliothek erforderlich",
    "noLanguagesInRegion": "Für diese Region sind noch keine Sprachen aufgeführt.",
    "toggleTheme": "Theme wechseln",
    "productsYouWant": "Gewünschte Produkte", "productsYouHave": "Besessene Produkte",
    "myOffers": "Meine Angebote", "priceDrops": "Preisbenachrichtigungen",
    "myCollections": "Meine Sammlungen", "newCollection": "Neue Sammlung...",
    "creditsClub": "Credits Club", "savedOrders": "Gespeicherte Bestellungen",
    "myQuestions": "Meine Fragen", "myReviews": "Meine Bewertungen",
    "myFriends": "Meine Freunde", "viewProfileTooltip": "Dein Profil ansehen",
    "userMenuCaretAlt": "Benutzermenü öffnen",
    "backToTop": "Nach Oben",
    "bestpriceSloganShort": "Der wirklich beste Preis",
    "bestpriceSloganLong": "BestPrice ist der erste und größte Preisvergleichsdienst in Deutschland.",
    "bestpriceSloganFindDeals": "Bei BestPrice finden Sie schnell und einfach echte Angebote und den besten Preis von den größten Shops.",
    "bestpriceGive": "BestPrice Give", "footerBestPriceSectionTitle": "BestPrice",
    "aboutUs": "Über Uns", "ourBlog": "Unser Blog",
    "buyingGuides": "Kaufberater", "purchaseInsurance": "Kaufversicherung",
    "advertising": "Werbung", "bestpriceCertification": "BestPrice Zertifizierung",
    "customerReviewAwards": "Kundenbewertungs-Awards", "ourAwards": "Unsere Auszeichnungen",
    "ourTeam": "Unser Team", "bestpriceAssistant": "BestPrice Assistent",
    "jobOpenings": "Stellenangebote ({{count}})", "contactUs": "Kontakt",
    "inNumbers": "In Zahlen",
    "storeCountLink": "{{count}} Shops", "productCountLink": "{{count}} Produkte",
    "brandCountLink": "{{count}} Hersteller","dealCountLink": "{{count}} Angebote",
    "termsAndPrivacy": "AGB & Datenschutz", "termsOfUse": "Nutzungsbedingungen",
    "privacyPolicy": "Datenschutzrichtlinie", "cookiePolicy": "Cookie-Richtlinie",
    "gdprLink": "DSGVO", "dsaLink": "DSA",
    "bestpriceForMerchants": "BestPrice Für Händler",
    "merchantsSectionSlogan1": "Haben Sie einen Online-Shop?",
    "merchantsSectionSlogan2": "Erfahren Sie, wie BestPrice Ihnen helfen kann, Ihren Umsatz zu steigern!",
    "forMerchantsButton": "Für Händler",
    "bestpriceForBrands": "BestPrice Für Marken",
    "brandsSectionSlogan": "BestPrice für Marken bietet Herstellern (Marken) nützliche Informationen und Dienstleistungen.",
    "moreInfoButton": "Mehr Infos",
    "bestpriceOnFacebook": "BestPrice auf Facebook", "bestpriceOnX": "BestPrice auf X",
    "bestpriceOnThreads": "BestPrice auf Threads", "bestpriceOnInstagram": "BestPrice auf Instagram",
    "bestpriceOnTikTok": "BestPrice auf TikTok", "bestpriceOnYouTube": "BestPrice auf YouTube",
    "bestpriceOnLinkedIn": "BestPrice auf LinkedIn",
    "homepageTitle": "Startseite",
    "changeLanguage": "Sprache Ändern", "selectYourLanguageTitle": "Wählen Sie Ihre Sprache",
    "suggestedLanguages": "Vorgeschlagene Sprachen", "allLanguages": "Alle Sprachen",
    "languageCategoryEurope": "Europa", "languageCategoryAsia": "Asien",
    "languageCategoryAmericas": "Amerika", "languageCategoryAfrica": "Afrika & Naher Osten",
    "languageCategoryEasternEurope": "Osteuropa", "languageCategoryWesternEurope": "Westeuropa",
    // ... (All other keys from 'en'/'el' translated to 'de')
    'technology': 'Technologie', 'home-garden': 'Haus und Garten', // ... ALL CATEGORY SLUGS ...
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'el',
  setLanguage: () => {},
  translations: defaultTranslations,
  isLoaded: false,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('el');
  const [translations, setTranslations] = useState<Translations>(defaultTranslations);
  const [isLoaded, setIsLoaded] = useState(false);
  const { user } = useAuth();

  useEffect(() => {
    const detectLanguage = async () => {
      let detectedLang: Language = 'el';
      const browserLang = navigator.language.split('-')[0];
      if (['en', 'el', 'es', 'fr', 'de'].includes(browserLang)) {
        detectedLang = browserLang as Language;
      }
      if (user) {
        try {
          const { data, error } = await supabase.from('profiles').select('language').eq('id', user.id).single();
          if (data?.language && !error) { detectedLang = data.language as Language; }
        } catch (error) { console.error('Error fetching user language preference:', error); }
      }
      const savedLang = localStorage.getItem('language') as Language;
      if (savedLang && ['en', 'el', 'es', 'fr', 'de'].includes(savedLang)) {
        detectedLang = savedLang;
      }
      setLanguageState(detectedLang);
      setIsLoaded(true);
    };
    detectLanguage();
  }, [user]);

  useEffect(() => {
    const loadCustomTranslations = async () => {
      // Only attempt to set defaults if translations are truly the initial empty or default reference
      // AND isLoaded is false (meaning this is likely the very first effect run for translations)
      if (!isLoaded && (Object.keys(translations).length === 0 || translations === defaultTranslations )) {
         setTranslations(defaultTranslations);
      }

      try {
        const { data, error } = await (supabase as any).from('translations').select('*');
        if (error) {
            console.error('Error fetching custom translations:', error.message || error); // Log more details
            // Fallback to defaults only if no custom translations were successfully loaded before
            if (translations === defaultTranslations || Object.keys(translations).every(lang => Object.keys(translations[lang]).length === Object.keys(defaultTranslations[lang]).length)) {
              setTranslations(defaultTranslations);
            }
            return;
        };
        if (data && data.length > 0) {
          // Start with a deep copy of default to ensure all keys exist, then override with DB data
          const newLoadedTranslations = JSON.parse(JSON.stringify(defaultTranslations)) as Translations;
          data.forEach((item: any) => {
            if (item && item.key) {
              (Object.keys(newLoadedTranslations) as Language[]).forEach(lang => {
                if (item[lang] && typeof item[lang] === 'string') {
                  newLoadedTranslations[lang][item.key] = item[lang]; // DB overrides default
                }
              });
            }
          });
          setTranslations(newLoadedTranslations);
        } else {
           // No custom translations from DB, ensure defaults are set if not already properly initialized.
           if (translations === defaultTranslations || Object.keys(translations).every(lang => Object.keys(translations[lang]).length === Object.keys(defaultTranslations[lang]).length)) {
            setTranslations(defaultTranslations);
          }
        }
      } catch (error) {
        console.error('Error processing custom translations:', error);
         if (translations === defaultTranslations || Object.keys(translations).every(lang => Object.keys(translations[lang]).length === Object.keys(defaultTranslations[lang]).length)) {
          setTranslations(defaultTranslations);
        }
      }
    };

    if (isLoaded) { // Attempt to load custom translations once isLoaded is true
        loadCustomTranslations();
    } else if (Object.keys(translations).length === 0) { // On very first mount before isLoaded might be true
        setTranslations(defaultTranslations);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLoaded]); // Only re-run if isLoaded changes.

  const setLanguage = useCallback((lang: Language) => {
    localStorage.setItem('language', lang);
    setLanguageState(lang);
    if (user) { 
      supabase.from('profiles').update({ language: lang } as any).eq('id', user.id)
        .then(({ error }) => { if (error) { console.error('Error saving language preference:', error); } });
    }
  }, [user]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations, isLoaded }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguageContext = () => useContext(LanguageContext);
